### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-utils#10]
I think it's pretty clear that we need tests for the build system to avoid crippling the main bioconda-recipes repo.  Quicker-running tests here will also allow faster development iterations than trying to test full bioconda-recipes PRs.

I'm thinking of setting up several small recipe dirs in this repo, a corresponding bioconda-utils channel on anaconda that can be pre-populated and used for testing for existing packages, and possibly a bioconda-utils docker hub account for at least tinkering with docker containers. The latter is so it will be isolated from the main bioconda-recipes repo while we work out how best to build.

@johanneskoester would you mind setting up a bioconda-utils channel and possibly a dockerhub account for this?  For now we can copy the existing `.travis.yaml` structure (with subdags and encrypted env vars), so "setup" would mean committing a `.travis.yaml` with the new keys for this repo and conda channel, and pointing dockerhub to a Dockerfile in this repo.

**Comment by johanneskoester** [comment]
I agree. We need rigorous tests before using any new version in the recipes repo. Your plan sounds good. Regarding the separate channel, I have a more lightweight solution, see PR #12.
With the docker hub account, let's wait if we really need it. At the moment, I still hope to sort out all problems with the conda-builder at the client side (chown).

**Comment by daler** [comment]
Tests are in decent shape, closing this.
