### ISSUE TITLE
Update pinned conda-build version?

### ISSUE THREAD

**Issue by acaprez** [bioconda/bioconda-utils#124]
I was wondering if it would be possible to update the `conda-build` version to >=2.0.11?  I'm working on a recipe and hitting a bug that was fixed in v2.0.11 which causes the build to fail.

**Comment by bgruening** [comment]
We tried this here: https://github.com/bioconda/bioconda-utils/pull/123
But 2.0.11 has a new bug :(

**Comment by chambm** [comment]
Do you feel like this sometimes?
![image](https://user-images.githubusercontent.com/5011937/26850526-68d91d5e-4acd-11e7-80ad-7c0806db4033.png)

**Comment by bgruening** [comment]
:smile:

**Comment by acaprez** [comment]
Oof, that's unfortunate.  Ok, I'll close this then and just wait until the bugs are fixed with the newer version.  Thanks!
