### ISSUE TITLE
Provide documentation on how to build bioconda binaries for local / private use

### ISSUE THREAD

**Issue by amcpherson** [bioconda/bioconda-utils#125]
I would like to be able to build a substantial portion of the bioconda binaries for use on a Centos5 system that cannot be upgraded to Centos6.  Would it be possible to use bioconda-utils for this? And if so could such a use case be documented?

**Comment by johanneskoester** [comment]
This should do:
```
cd bioconda-recipes
bioconda-utils build recipes config.yaml --packages $YOURPACKAGES
```

Adding this to the docs is a good idea, indeed.

**Comment by bgruening** [comment]
Alternatively, you can also set https://github.com/bioconda/bioconda-recipes/blob/master/config.yml#L8 to a Docker container with CentOS-5 and run it with `--docker`. However, the real challenge is that BioConda depends on `conda-forge` and you also have to recompile all dependencies from them and in the worst also from `defaults`.

**Comment by amcpherson** [comment]
@johanneskoester thanks i did try that (should have specified).

```
bioconda-utils build recipes config.yml --packages pysam
06:55:56 BIOCONDA INFO blacklist: bioconductor-bubbletree, bioconductor-cexor, bioconductor-deseq2/1.10.1, bioconductor-genelendatabase/1.6.0, bioconductor-iranges/2.4.6, bioconductor-iranges/2.4.7, bioconductor-limma/3.26.7, bioconductor-limma/3.28.2, bioconductor-limma/3.28.6, bioconductor-mmdiff, bioconductor-s4vectors/0.8.7, bioconductor-summarizedexperiment/1.0.2, blast/2.2.21, cap-mirseq, denovogear, detonate, gdsctools, mothur/1.36.1, mysqlclient, perl-font-afm, r-hdrcde, r-knitr, r-ks, r-mutoss, r-phonr, r-rainbow, r-readr, r-sartools/1.2.0, triform2
06:55:56 BIOCONDA INFO Filtering recipes

Filtering 4 of 4 (100.0%) recipes/pysam/0.9.1
06:56:00 BIOCONDA INFO Nothing to be done.
```

It appears it attempts to determine whether the package has already been built and skips it?

**Comment by daler** [comment]
There are a few other things scattered throughout that are specific to bioconda that make it not so straightforward to use for another channel, like encrypted tokens in the `bioconda-recipes`'s travis config and hard-coded repos and branches to check. It is certainly possible to use this with another repo, and that's always been the intention. We just haven't documented it yet and pulled out all the config into a single place.

Here are some places that would need changing to a different repo/channel:

- https://github.com/bioconda/bioconda-utils/blob/7d34d35c49d4fae389dc06da63db56292f255389/bioconda_utils/utils.py#L430
- https://github.com/bioconda/bioconda-utils/blob/7d34d35c49d4fae389dc06da63db56292f255389/bioconda_utils/linting.py#L110
- https://github.com/bioconda/bioconda-utils/blob/7d34d35c49d4fae389dc06da63db56292f255389/bioconda_utils/utils.py#L382
- https://github.com/bioconda/bioconda-utils/blob/7d34d35c49d4fae389dc06da63db56292f255389/bioconda_utils/docker_utils.py#L141
- https://github.com/bioconda/bioconda-utils/blob/7d34d35c49d4fae389dc06da63db56292f255389/bioconda_utils/cli.py#L144

**Comment by epruesse** [comment]
Closing as the specific use case - building for Centos5 - is likely nigh impossible because of `conda-forge` dependencies.
