### ISSUE TITLE
Check pins in linter

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-utils#142]
There are a number of packages with versions known to break things. While they can't be removed, the linter can check that they are excluded via pinning by any updated recipe.

A good start would be the list hidden away in conda-forge's [`pin_the_slow_way.py`](https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/pin_the_slow_way.py#L39). Adding to that, there are broken bioconda packages as well, such as `sed 4.2.0` (pin to 4.4.*).

**Comment by johanneskoester** [comment]
We could also mark those packages as broken on anaconda. This way, they won't be pulled without explicitly requiring them by selecting the `broken` label. @bioconda/core, what do you think?

**Comment by jerowe** [comment]
I like the idea of deprecating packages as broken. It makes it so the user really has to want it to get it, and if they have specific enough reasons for wanting it then they have been warned.

**Comment by daler** [comment]
I think this is a great idea. It would also be useful to include some of those into the `env_matrix.yml` for pinning.

**Comment by johanneskoester** [comment]
I totally agree. I just don't have the time to work on this in July :-(.

**Comment by bgruening** [comment]
Considering the space issue we currently have I would avoid large rebuilds as much as possible. I suppose we will do a big rebuild with conda-build 3 and align closely to conda-forge, isn't it?

**Comment by epruesse** [comment]
>I think this is a great idea. It would also be useful to include some of those into the env_matrix.yml for pinning.

Maybe the other way round, so that linting can check for those properly. 
Mirroring the blacklists, we could have 

 - a `pinlists:` section in `config.yaml` specifying pinning files
   ```
    pinlists:
       - bioconda-pinned
       - conda-forge-pinned
   ```
 -  pinning file(s) with lines like 
     ```
     zlib 1.2.8
     boost 1.64
     ```
 - `utils.EnvMatrix` derives `CONDA_ZLIB=1.2.8` environment variables from this
 -  `lint_functions.missing_pins` checks that recipes with `zlib` have `{{CONDA_ZLIB}}` set
 - eventually, a mechanism akin to "recently unblacklisted" recompiling if pins change

**Comment by epruesse** [comment]
Outdated by CB3
