### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'split'

### ISSUE THREAD

**Issue by sebastian-luna-valero** [bioconda/bioconda-utils#157]
Hi,

I get an AttributeError exception when doing:
```
bioconda-utils build recipes config.yml --mulled-test --packages cgat-scripts
```

Full output is [here](https://github.com/bioconda/bioconda-utils/files/1176975/output.txt)

I think the error was caused after adding a `pip` dependency on my `meta.yaml` file, like
```
requirements:
   build:
      - python 3.5
      - pip
         - bx-python==0.7.3
```

Do you know why?

Best regards,
Sebastian

**Comment by daler** [comment]
looks like you have an extra indentation on the `bx-python` line

**Comment by sebastian-luna-valero** [comment]
Sorry, I meant:
```
requirements:
   build:
      - python 3.5
      - pip:
         - bx-python==0.7.3
```

I guess, I should rephrase my question. How can I included `pypi` deps in the `meta.yaml`?

It works in a [conda environment file](https://conda.io/docs/using/envs.html#create-environment-file-by-hand).

**Comment by sebastian-luna-valero** [comment]
@daler could you please let me know your thoughts on this issue?

**Comment by daler** [comment]
Ah, sorry I misunderstood. Pip dependencies work in a conda env file but this is not supported (that I know of) by conda when building recipes. Anyway I think it's better to have checksummed downloads be the only input to a recipe rather than arbitrary pip packages.

For a recipe, any deps need to be in either defaults, conda-forge, or bioconda channels. But if you're looking specifically for bx-python, it's in bioconda (https://anaconda.org/bioconda/bx-python).

**Comment by sebastian-luna-valero** [comment]
Thanks @daler 

The thing is that our scripts depend on `bx-python` for certain tasks. We have ported our scripts from Py2 to Py3, but `bx-python` is not officially Py3 yet [1]. Therefore, the bioconda package is only Py2 [2]. However, we found that you can still pip install bx-python with Py3 and it does the job. Obviously this is a temporary solution until `bx-python` is fully ported to Py3.

On the other hand, I don't understand why pip dependencies are not supported when building recipes, if the version of the pip package is fixed. We need `bx-python=0.7.3`

Any suggestions?

[1] https://github.com/bxlab/bx-python/issues/9
[2] https://github.com/bioconda/bioconda-recipes/issues/1639

**Comment by daler** [comment]
If you run `conda-build` on your recipe directly, you will get an error like:

```
Received dictionary as spec. Note that pip requirements are not supported
in conda-build meta.yaml.
```

Installing from pip is not supported by `conda-build` for building packages from recipes. It's only supported by `conda` when building environments from requirements files.

An individual recipe can install from pip (that's how pretty much all python packages in bioconda are built). If you want bx-python on py3, then you need a working recipe and package for bx-python on py3. You can try getting a py3 package to run and pass tests, and work with upstream as necessary to get that to work.

**Comment by sebastian-luna-valero** [comment]
Thanks @daler
