### ISSUE TITLE
a working conda-build with docker

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-utils#17]
We were previously running into chown/permission issues when trying to run a docker container from inside a python script (see [this issue in the docker repo](https://github.com/docker/docker/issues/2259) for examples of others hitting the same problem). 

The idea was to have a docker container do all the building, but the built packages would be placed in the host's conda-bld dir. That is, a `conda build $recipe` command that used a CentOS5/6 container to build, independent of the host OS.

I wanted to start simple, so I created a new repo at https://github.com/daler/build-test, which is now working on travis-ci and does exactly this. In fact, conda-build is not even installed on the travis-ci instance, and conda is only installed to test that the package is conda-installable. The slightly hacky part is building a new, local container each time based on the uid:gid of the user running the script. But it's fast, and it works.

So @johanneskoester, @bgruening if you guys think this is still a useful thing for bioconda-utils I can work on porting it over.

**Comment by bgruening** [comment]
Neat! I think this is still useful, but I would like to wait a little bit until we have done and tested the other things. There is so much stuff going on currently and we do not have R3.3 yet. Don't get me wrong, but I would like to keep the complexity low for the moment until we have solved all the other things.

**Comment by daler** [comment]
Might seem gimmicky, but I was actually hoping this would make testing more robust and decrease overall complexity since there would only be one way to build recipes whether locally or on travis-ci. For example, right now there's not really a good way to get a conda package built using the CentOS container that can then be locally conda-installed and tested more thoroughly, other than doing the whole PR/travis-ci merge dance.

This would help lower the bar for troubleshooting, since folks could make changes and test recipes locally without having to learn our build infrastructure and wait for PR merges to have their CentOS-built packages available to download from bioconda channel for local testing. It would also hopefully speed up recipe development.

Not saying it should be added in now, just trying to explain that there was some strategy behind this :)

**Comment by johanneskoester** [comment]
Sounds great! I would also like to have this merged to bioconda utils as soon as possible. Of course not without careful testing. If it works nicely I would also agree to do that before the conda-build 2.0/R3.3 marathon.

**Comment by bgruening** [comment]
Good point :)
I'm still traumatized by our the last Docker bioconda try.

**Comment by johanneskoester** [comment]
I hear you :-)). 

OT: I guess I see you tomorrow at ECCB. If we don't find each other in the morning, make sure to visit me at my poster P_Da015.

**Comment by bgruening** [comment]
I will find you :)

**Comment by kyleabeauchamp** [comment]
Is your poster available online anywhere?  Could be useful for the snakemake / bioconda wikis.

**Comment by johanneskoester** [comment]
Thanks for the interest! It is linked at the Snakemake homepage now.

**Comment by bgruening** [comment]
don't forget to upload it to the F1000 channel.

**Comment by johanneskoester** [comment]
Thanks for reminding, done!

**Comment by daler** [comment]
This has been implemented for a while now, closing.
