### ISSUE TITLE
Tests are skipped for pushes to the main bioconda-recipes repo.

### ISSUE THREAD

**Issue by sebastian-luna-valero** [bioconda/bioconda-utils#173]
Hello,

After re-reading the docs here:
http://bioconda.github.io/contribute-a-recipe.html#update-repo

I thought one can now push directly to `bioconda-recipes` without a fork. At least, that's what I understood from the following bit:

>  If you’re using a clone:
```
git checkout master
git pull origin master
```

However, after doing that I get: `Tests are skipped for pushes to the main bioconda-recipes repo.`

Could you please clarify this?

Many thanks,
Sebastian

**Comment by sebastian-luna-valero** [comment]
For our reference, this is happening here:
https://github.com/bioconda/bioconda-recipes/pull/5894

Travis output is here:
https://travis-ci.org/bioconda/bioconda-recipes/jobs/269935560

**Comment by bgruening** [comment]
I see tests running for this PR? There are actually two tests, one that is cancelled very early on for the branch and one for the PR maybe this was confusing.

**Comment by sebastian-luna-valero** [comment]
Thanks @bgruening and sorry for the noise.
