### ISSUE TITLE
Using bioconda-utils as a site specific package builder

### ISSUE THREAD

**Issue by jerowe** [bioconda/bioconda-utils#176]
pinging @bioconda/core 

This is mostly just a shout out for the great work you've done on infrastructure. ;-)

We are going to be using the bioconda-utils package and build system (including mulled builds and whatnot), as a way of building our analysis/lab/project packages, which are just meta packages of bioconda and sometimes R packages. Initially we were just using conda-envs, but that has proven to be problematic if things change upstream, so instead, we will just build packages and leave them there. 

I've been taking a look at the code, and it looks likes its ready for being site specific. I think I should only have to change some of the variables in the scripts/travis-run.sh script, and of course the .travis needs to have our own github token and things, but I will let you know if you run into any snags.

**Comment by johanneskoester** [comment]
Great. I think we are all happy to merge any changes that make bioconda-utils more configurable and remove hardcoded values.

**Comment by johanneskoester** [comment]
Btw. for [Snakemake](https://snakemake.bitbucket.io), I have developed a way to snapshot a conda env and package it in a portable way for e.g. upload to [zenodo](https://zenodo.org). If that is of interest for you, one could probably also think about separating this out into a standalone tool.

**Comment by jerowe** [comment]
@johanneskoester  - that could be interesting. I still use conda-envs quite a bit. For a researcher the conda-env interface is more straight forward than creating a recipe, building it, and uploading it.

For the main infrastructure though I want the rest of what bioconda utils has to offer, mainly creating the docker, hopefully soon singularity containers, and when I can finally sit down and do it the easybuild configurations those too.

**Comment by jerowe** [comment]
So I finally sat down and got started on this today. I didn't even end up needing to change any code, just a bit of the travis-run.sh in the bioconda-recipes, so that was great! I would say I'm about 90% there. I just have a few questions.

What does the github integration do? Just comments? If its something that I want I will have to open a PR, because it does have a hardcoded 'bioconda' user within the code, that IMO a site should be able to change to their own user.

I see that the build_recipes takes an argument 'label', but I'm not sure how to get at those from the command line. Is it possible to add my own custom labels from the existing code/interface, or will I need to write an addon to the anaconda_upload function? 

The bioconda-utils is a really robust build system, and I think its a major perk for the community to be able to use the same build system with minimal changes and be create their own site specific meta packages.

**Comment by daler** [comment]
@jerowe thanks for going on that adventure! It would be great to have it be more generic. Honestly I'm (pleasantly) surprised that more things weren't hard-coded.

The github integration is what handles the bioconda-bot linting messages. This: https://github.com/bioconda/bioconda-utils/blob/3dfef175ff8fa5838d0e8c7d3c7e058b7e2c0dce/bioconda_utils/cli.py#L88 allows the user to be passed in via CLI, but maybe you're referring to the hard-coding here: https://github.com/bioconda/bioconda-utils/blob/3dfef175ff8fa5838d0e8c7d3c7e058b7e2c0dce/bioconda_utils/github_integration.py#L87? The latter one can probably be removed, I think that was for initial testing. Is there another hard-coding that you saw?

Exposing `label` to the CLI should be straightforward by adding an `@arg('--label'...)` decorator and kwarg to `cli.build` and passing it to the call to `build_recipes`: https://github.com/bioconda/bioconda-utils/blob/3dfef175ff8fa5838d0e8c7d3c7e058b7e2c0dce/bioconda_utils/cli.py#L276

Right now we just use `label` as a mechanism for testing the uploading and removal of packages without messing with the main packages in the channel. I think the only reason it's not exposed to the CLI is that we haven't had a use for it yet.

**Comment by jerowe** [comment]
@daler its already really generic, so no worries there! I have one small issue with quay uploads, but @bgruening was able to identify it very quickly for me.

If I was going to make a big change it would be to have the login in the bioconda-recipes/scripts/travis-run.sh in a bioconda-utils.build_args module, but only because I don't like dealing with bash.

```
bioconda-utils build `bioconda-utils build_args`
```
Does that make sense?

A user could of course pass whatever arguments they want with whatever logic they want, but it would clean up the travis-run and cut down on the boiler plate code needed for a site to maintain their own packages/metapackages build with the power of bioconda. ;-)

I would quite like the ability to have custom labels, but I understand if that is outside of the scope of the main bioconda-utils.

**Comment by daler** [comment]
@jerowe, I think this boils down to preference of python vs bash. How generic should we make the travis-ci logic? I feel like `travis-run.sh` describes a bioconda-specific workflow. But if that logic seems like it would be generic enough, then it could certainly stand to be cleaned up and repackaged. Would you want to change any of the logic in there for a site-specific install? More specifically, what if any args do you envision `bioconda-utils build_args` should take?

Custom labels should be trivial, I'll open a PR for that.

**Comment by jerowe** [comment]
It would logically be the same workflow. In my mind the only real gain is
reducing boilerplate for sites trying to reproduce the awesomeness of
bioconda.

I think it's possible to make the argument that the logic is somewhat
specific to the bioconda-utils application. So that is possibly a gain?

It being in python over bash is simply a  bonus for me, but I don't think
that should be a driving force.  ;)

On Nov 16, 2017 7:48 PM, "Ryan Dale" <notifications@github.com> wrote:

@jerowe <https://github.com/jerowe>, I think this boils down to preference
of python vs bash. How generic should we make the travis-ci logic? I feel
like travis-run.sh describes a bioconda-specific workflow. But if that
logic seems like it would be generic enough, then it could certainly stand
to be cleaned up and repackaged. Would you want to change any of the logic
in there for a site-specific install? More specifically, what if any args
do you envision bioconda-utils build_args should take?

Custom labels should be trivial, I'll open a PR for that.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bioconda/bioconda-utils/issues/176#issuecomment-344964427>,
or mute the thread

**Comment by jerowe** [comment]
I changed the "bioconda/bioconda-recipes" to the environmental variable
MY_TRAVIS_REPO_SLUG in the travis-run.sh. I also had to change the quay.io
name space from biocontainers to nyuad-cgsb

**Comment by jerowe** [comment]
```
We also have isolated bioconda-utils from bioconda-recipes to better facilitate testing of the infrastructure, and to (one day!) make it general enough that others can use the framework for their own specific channels.
```
That day is today!

**Comment by bgruening** [comment]
Nice, glad this entire system works! Enjoy your containers!

**Comment by epruesse** [comment]
I think this works mostly now, so closing.

We might need a unit test or two though to make sure we aren't breaking things for people using `bioconda-utils` for repos other than `bioconda/bioconda-recipes`.
