### ISSUE TITLE
use a patched condarc

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-utils#181]
As described in [this conda issue](https://github.com/conda/conda/issues/5536), solver hangups can be avoided by modifying `.condarc`. This problem may be happening in https://github.com/bioconda/bioconda-recipes/pull/5926, but even if not, we should have an easy and robust way of modifying a user's condarc to meet the channel order criteria.

Options for modifying:

- `curl $github_url > ~/.condarc` is the easiest but also most disruptive to existing condarc
- `bioconda-utils setup-condarc` can parse the existing yaml and update as needed (or warn about potential problems)
- some sort of `curl $url | bash` thing that would, using bash, fix the condarc. Or maybe we can stick a minimal yaml parser into a single python module, and use that? Ideally it would be a no-dependency script.

@bioconda/core any preferences?

**Comment by epruesse** [comment]
Closing due to age - also, we've got that FAQ issue regarding conda performance now (not referencing to avoid spam on that side)
