### ISSUE TITLE
Add `conda verify` to test pipeline

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-utils#19]
https://www.continuum.io/blog/developer-blog/verifying-conda-recipes-and-packages-anaconda-verify

**Comment by johanneskoester** [comment]
Absolutely!! I wasn't aware of that. We should just put it into bioconda-utils before uploading a package.

**Comment by epruesse** [comment]
I think this is now `conda verify`. We should indeed run this, both on the recipe and on the binaries I think.

**Comment by epruesse** [comment]
The catch here is that `conda-verify` pulls in click.

**Comment by epruesse** [comment]
Fixed in c7a872aadb7575198b97950a1061932826dcafe7
