### ISSUE TITLE
bioconda package for bioconda-utils?

### ISSUE THREAD

**Issue by tomkinsc** [bioconda/bioconda-utils#20]
Would it make sense to have a conda package for bioconda-utils, so it can be installed as easily as `conda-build`? If we make one, the recipe could include `anaconda-verify` as a dependency to support #19.

**Comment by daler** [comment]
Sure, I suppose if conda-build builds conda-build we could have bioconda-utils build bioconda-utils.

**Comment by epruesse** [comment]
@daler I think this can be closed.
