### ISSUE TITLE
Free-for-academic license prompt on install

### ISSUE THREAD

**Issue by nickp60** [bioconda/bioconda-utils#206]
Hi all,
So this is a big feature request that has probably already been discussed in depth, but how hard would it be to add a license confirmation step to the install process?

I have been talking with BaseClear, the folks who make SSPACE and GapFiller, and they would be cool with having their stuff available through Bioconda only of there was an extra step for users to explicitly confirm that they aren't commercial users.

I would envision that during the install process there could be a prompt added ("This software is made available by BaseClear free of charge for academic users.  Do you confirm you are an academic user and to the terms of the license? (Yes|no|read license)")

Sorry for my ignorance of this is already been discussed to death!

**Comment by peterjc** [comment]
I don't know if this has been discussed extensively, perhaps before I started using contributing to BioConda? Licensing ought to be on https://bioconda.github.io/contributing.html somewhere but is not as far as I could see.

Personally I think the more idealistic stance of not packaging  "free for academic use" or "free for commercial use" clause tools is worth considering. In many cases such tools' license prevents redistribution of the software anyway, so we are not allowed to package it.

That said, for cases like this, a prompt of some kind seems worth considering.

e.g. New field in ``meta.yaml`` about prompting user explicitly to agree to the license (with option to view the licence text via the ``license_file`` metadata?)

In the context of Galaxy wrappers, some wrapper authors have pushed this onto the end user as a check box in the interface, others push this responsibility onto the systems administrator to handle installation and compliance.

Cross reference https://github.com/bioconda/bioconda-recipes/issues/1581 for more consistency in licensing labels.

**Comment by chambm** [comment]
Anything that makes the download or install process interactive would break in unexpected ways. In Galaxy, downloading and installing of bioconda dependencies is all automated and opaque to the end user.

**Comment by peterjc** [comment]
Don't we have examples of this already, e.g. GATK v3 as per https://bioconda.github.io/guidelines.html#other-examples-of-interest

> gatk is a package for licensed software that cannot be redistributed. The package installs a placeholder script (in this case doubling as the jar wrapper) to alert the user if the program is not installed, along with a separate script (gatk-register) to copy in a user-supplied archive/binary to the conda environment

Related to this, https://bioconda.github.io/guidelines.html#link-and-unlink-scripts-pre-and-post-install-hooks suggests using ``post-link.sh``, e.g. ``slncky/post-link.sh`` and ``dfam/post-link.sh`` but these seem to be non-interactive.

I suppose you could have a convention about ``post-link.sh`` requiring creation of a file at ``$PREFIX/LICENSE_AGREED.txt`` and the tool's wrapper script checking for the existence of this file before running the tool?

**Comment by epruesse** [comment]
It comes down to this: If the license allows Bioconda to distribute, we will, and it's up to the user to comply with the license. If it requires that the user be shown a license, the package maintainer needs to make sure of that, e.g. by  adding a wrapper around the main binary(ies) that keeps posting it or using `post-link.sh`. We can't police commercial or non-academic users, though, so if in doubt we would just not package/distribute and will immediately remove packages from the index if the copyright holders ask us to.
