### ISSUE TITLE
linters

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-utils#23]
Need linters for existing recipes to flag easily-identified issues.

For example, if gcc is a dependency, then llvm should be a dependency for osx and libgcc should be a run dependency.

I'm picturing this as a module of functions that each take a recipe and check for a discrete issue, returning a list of issues identified. Adding new functionality to the linter would be a matter of just adding a new function.

**Comment by daler** [comment]
List of linter functions to add, please edit and add more:

- hash must exist
- license flagged if not in controlled vocabulary list of licenses

**Comment by bgruening** [comment]
@daler here are a few ideas: https://github.com/bioconda/bioconda-recipes/issues/1860

**Comment by daler** [comment]
thanks, was just looking for that issue :)

**Comment by peterjc** [comment]
Another suggestion:

* Check valid formatting for dependency versions

e.g. preempt ``conda.exceptions.CondaRuntimeError: Runtime error: Invalid version spec: >=`` from ``libgd >= 2.2`` rather than ``libgd >=2.2`` on https://github.com/bioconda/bioconda-recipes/pull/4655

**Comment by epruesse** [comment]
Closed as all but the "license flagged if not in controlled vocabulary list of licenses" lint now exist.
