### ISSUE TITLE
pre-unlink script for Bioconductor data packages

### ISSUE THREAD

**Issue by mbargull** [bioconda/bioconda-utils#234]
While looking at the fixes @jdblischak provides for the Bioconductor skeleton I noticed that only a `post-link.sh` but not a corresponding `pre-unlink.sh` is created.
I guess Conda won't be able to track changes make by `post-link.sh`, thus uninstalling a data package may not remove it properly.
(Note that acc. to https://conda.io/docs/user-guide/tasks/build-packages/link-scripts.html
> `pre-unlink`—Executed before the package is removed. An error is indicated by a nonzero exist and causes the removal to fail.

which would mean one should take care to make those not fail easily to not create "uninstallable" packages -- however `conda` will actually only output a warning and carry on, see:
https://github.com/conda/conda/blob/6807e91d36a125d19248acdecac960c0c7c2dd55/conda/core/link.py#L494-L517
)

**Comment by jdblischak** [comment]
> thus uninstalling a data package may not remove it properly.

@mbargull I did a quick test to confirm your suspicion. While removing the Bioconductor package with `conda remove` makes it forgotten by conda, the package still exists untouched and able to be loaded by R.
