### ISSUE TITLE
Newest condaforge/linux-anvil image causes permission denied when testing locally

### ISSUE THREAD

**Issue by acaprez** [bioconda/bioconda-utils#246]
I ran into `permission denied` errors recently when testing a new recipe using `simulate-travis.py` with Docker.  This occurred at the end of the build, when the built package is copied back to the host via a Docker volume.  After a little digging, the new `linux-anvil` image that was released a few days ago apparently changed the way processes are run in the container.  Previously, everything was run as `root`; now they are run as the `conda` user, with a default UID of 9001.  This causes the permission denied error when trying to copy the built package(s) back to the host via the mounted volume at `/opt/host-conda-build` within the container.  (My test VM setup is F25 with Docker 17.05.0-ce.  Everything is run as the `fedora` user with UID 1000.)

The entrypoint script that does the magic is [here](https://github.com/conda-forge/docker-images/blob/master/linux-anvil/entrypoint).  They do provide a mechanism to avoid the problem via a `HOST_USER_ID` variable that can be passed in, in order to match the `conda` user UID inside the container to the UID of the real user outside.  As a fix then, I did the following:

1)  Added `HOST_USER_ID` to the `ENV_VAR_WHITELIST` list in `utils.py`
2)  Ran `` export HOST_USER_ID=`id -u` `` before running `simulate-travis.py`

That resolved the problem and the build worked normally.  (It might be a good idea to set the `HOST_USER_ID` variable automatically somewhere inside `simulate-travis.py` for simplicity.)

**Comment by bgruening** [comment]
@acaprez thanks for investigation. I can confirm this is a nice workaround. You or me up for a PR :)

**Comment by daler** [comment]
@acaprez thanks for this! @bgruening I'm working on the PR now.

**Comment by acaprez** [comment]
@daler - oops, I just opened a PR to add the var (#247).  Should I just close it?

**Comment by bgruening** [comment]
Should be fixed by: https://github.com/bioconda/bioconda-utils/pull/247

**Comment by acaprez** [comment]
Fixed by #247
