### ISSUE TITLE
Adding citation information to packages

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-utils#252]
For various reasons, it would be neat to have `cite-as` or `doi` type information with our packages (e.g. `conda env citations -n mouse-analysis`). I've asked at conda, and they wouldn't object to extending the `about:` section, but need someone to do a PR.

See conda/conda-build#2630

I'm thinking that it would be very easy to query `doi.org` from within conda-build for the appropriate citation data given a DOI, so for most packages, just filling that in would allow populating a meta-data structure that would be exported into the conda-meta/<package>.json file for later processing. 

@bioconda/core  - would love to have some brainstorm votes before I try anything

 - What should be the name of the field? (`cite-as`, `citation`, `reference`, `doi`)
 - Should the field be just a DOI, or an entire reference data structure?
 - If an entire structure, should it be auto-filled from DOI using `doi.org`?
 - If a structure, what fields should there be? (Easy options: match the json returned from doi.org, or match bibtex format like R's `citation()` command)

**Comment by peterjc** [comment]
+1 for supporting DOI only as the _recommended_ option, but that will not cover everything.

For a very similar use case, Galaxy tool wrapper XML files have an optional citation field. Herea DOI is preferred, but Galaxy also accepts a bibtex entry (its not perfect, but a reasonable widely supported standard). e.g.

```xml
<citations>
   <!-- Example of annotating a citation using a DOI. -->
   <citation type="doi">10.1093/bioinformatics/btq281</citation>

   <!-- Example of annotating a citation using a BibTex entry. -->
   <citation type="bibtex">@ARTICLE{Kim07aninterior-point,
   author = {Seung-jean Kim and Kwangmoo Koh and Michael Lustig and Stephen Boyd and Dimitry Gorinevsky},
   title = {An interior-point method for large-scale l1-regularized logistic regression},
   journal = {Journal of Machine Learning Research},
   year = {2007},
   volume = {8},
   pages = {1519-1555}
   }</citation>
 </citations>
```

See https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-citations for further details. Ping @jmchilton who if memory served did the initial implementation.

**Comment by bgruening** [comment]
@epruesse `doi` sounds also nice to me. And we could have different ones, like @peterjc mentioned the bibtex one. `doi` I actually think should be in the about section ideally.

Also please see this idea: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/locarna/biotools.yaml

Which was an attempt to get more metadata added, but more optionally and aligned with bio.tools.

**Comment by epruesse** [comment]
@bgruening I don't think I'd want different types to mess with. The BibTex structure has a `doi` field, and leaving fields empty seems necessary anyway. Going with BibTex style format, that leaves the question whether the remainder of the fields should be auto-populated by querying `doi.org` or whether that should just be left out as redundant. (I feel it would be useful, just so the data is there to be searched without querying APIs a lot later.)

**Comment by peterjc** [comment]
I would strongly prefer using a single DOI field if available over (even a minimal) BibTex style format. It is easier for the user, and for many potential downstream analyses (e.g. compiling a citation list for a conda environment where you'd want to remove any duplicates - most formats including BibTex have too much leeway in formatting).

I think Galaxy got the usability right - DOI to cover all the easy cases, with text field based manual fallback (BibTex format).

**Comment by bgruening** [comment]
What @peterjc is saying was what I wanted to say ... bibtex should be the last resort :) DOI should be the preferred way, imho.

**Comment by epruesse** [comment]
Looks like there is a clear preference to just have the doi. That's easiest too.

+1 this comment if you prefer

```
about:
   doi:
```

**Comment by epruesse** [comment]
or this comment if you prefer
```
  about:
     cite-as:
         doi:
         <optionally other bibtex fields>
```

**Comment by epruesse** [comment]
and +1 / -1 this comment if in the case of `cite-as: doi:` you would like `conda-build` to auto-fill the bibtex fields during build.

**Comment by bgruening** [comment]
@epruesse if we put it into the about section we need to discuss this with upstream and I'm all in for this. about/doi probably works.

**Comment by epruesse** [comment]
@bgruening Upstream confirmed that they would accept a PR. It'll take a while to be in a release and usable by us of course.

**Comment by bgruening** [comment]
@epruesse Awesome! Thanks a lot for pushing this!

**Comment by johanneskoester** [comment]
Nice idea, I like this a lot. I would even vote to exclusively support DOI. If there is no citable DOI, it should be fine to simply skip it. Or are there any journals that don't provide DOI's?

**Comment by peterjc** [comment]
There are a few niche scientific society reports, conference presentations, or small print run books without a DOI, for example the MIRA citation:

```
@ARTICLE{Chevreux1999-mira3,
author = {B. Chevreux and T. Wetter and S. Suhai},
year = {1999},
title = {Genome Sequence Assembly Using Trace Signals and Additional Sequence Information},
journal = {Computer Science and Biology: Proceedings of the German Conference on Bioinformatics (GCB)}
volume = {99},
pages = {45-56},
url = {http://www.bioinfo.de/isb/gcb99/talks/chevreux/main.html}
}
```

Rather than publications without a DOI, I suspect it more likely for software tools is there isn't yet a journal article to cite, or even a preprint. For software tools on GitHub, you can encourage the authors to get a DOI (as of a particular commit) via Zenodo, https://guides.github.com/activities/citable-code/

So, a DOI only system would miss a few cases - but would handle the majority very nicely, and be a big improvement to the metadata.

**Comment by peterjc** [comment]
Note you may sometimes want to record multiple citations, e.g. two DOI references.

**Comment by johanneskoester** [comment]
Yes, allowing multiple DOIs is a good idea. If there is no article at all, I think it is sufficient to just have the homepage as we have now. For those niche journals, I think we can ignore them. Bioconda is a modern system, and we should not put too much work in old stuff. In the end the DOI link will just be an additional, optional service.

**Comment by epruesse** [comment]
Ok, so it seems to me that there is consensus here to just go with `about: doi`. That's a simple one line patch in `conda-build` (plus perhaps a lint in `bioconda-utils` to make sure the doi exists).

@peterjc Do you think multiple DOIs is more than a corner case? Usually, the authors have one preferred publication and it's customary to not bloat a paper's references with the whole set of previous publications. Of the top of my head, I can't even think of an exception to this.

**Comment by epruesse** [comment]
Incidentally, does our linting have a way to show warnings? The usual catch with meta-data is it's tendency to be incomplete. Informing everyone on PR that we'd like to have the DOI may help to fill those in.

**Comment by johanneskoester** [comment]
Unfortunately not at the moment. I would ideally like to address this via an extension of githubs way of reporting CI results, but it might be that we will have to address it in a different way at some point.

**Comment by peterjc** [comment]
I'm sure I've seen a few software tools which asked you to cite two or three papers (I remember this because old fashioned journals often have arbitrary limits to the number of references), but right now I can't find a good example for you.

In trying to find such an example, I noticed how often tools which do specify their preferred citation are missing the DOI, which is a shame.

The closest example I could find to a multiple-citation request was, GATK quoting https://software.broadinstitute.org/gatk/documentation/article.php?id=6201

> To date we have published three papers on GATK (citation details below). You're welcome to choose which paper is most representative of what aspect of GATK you called on in your work; or if you have a hard time choosing, just use all as a triple citation, as in ...

In general were there is a choice of citations it is usually easy to pick a primary one for the packaging meta-data, e.g.
* Galaxy https://galaxyproject.org/citing-galaxy/
* Biopython http://biopython.org/wiki/Documentation#papers

High profile no DOI example, HMMER3 quoting http://eddylab.org/software/hmmer3/3.1b2/Userguide.pdf

> How do I cite HMMER?
> The appropriate citation is to the web site, hmmer.org. You should also cite what version of the software you used. ...
> There is not yet any appropriate citable published paper that describes the HMMER3 software suite.

**Comment by ypriverol** [comment]
@epruesse @bgruening @johanneskoester @peterjc 

On this topic. We have an ongoing discussion in bioconda (https://github.com/bioconda/bioconda-recipes/issues/7699) and biocontainers (https://github.com/BioContainers/specs/issues/84) about external references. I think the way of linking the current bioconda package to different _research objects_ like the publication related to the package or the tool should be the following approach: 

```yml
extra: 
   identifiers: 
      - biotools:abyss
      - doi:10.1101/gr.214346.116
      - http://bio.tools/abyss
```

A different topic is to assign an acutal doi to the conda recipe which can be a future/soon feature. This is a doi different to the publication doi. For that I acutally suggest to follow the appraoch proposed: 

```yml
about: 
   doi:whereve_doi_here
```

**Comment by bgruening** [comment]
@epruesse @peterjc can you comment on https://github.com/bioconda/bioconda-recipes/pull/7940
We would like to get this started :)

**Comment by epruesse** [comment]
I think starting with some info in `extra:` is good. Should something be added to `about:` we can always easily move data we already have one we actually use that version of `conda-build`.

**Comment by epruesse** [comment]
Cross posting from BioContainers/specs#92

W.r.t. identifiers vs URIs, as in `doi: 10.xxx/xxx` vs `https://doi.org/10.xxx/xxxx`: 

The former is officially deprecated in favor of the latter to increase visibility and ease of use. 

From https://www.crossref.org/display-guidelines/#why-not-use-doi-or-doi:

> Why not use doi: or DOI:?
> 
> When Crossref was founded in 2000 we recommended that DOIs be displayed in the format `doi:10.NNNN/doisuffix` and many members still use `doi:[space][doinumber]`, `DOI: [space][doinumber]`, or `DOI[space][doinumber]`. At the time that the DOI system was launched in the late 1990s it was thought that `doi:` would become native to browsers and automatically resolve DOIs, similar to `http:`. This never happened and it will never happen. Advantages to changing the display to a resolvable URL - even on the page the DOI itself resolves to - include the following:
> 
>   -  A DOI is both a link and an identifier. Users will more easily recognize Crossref DOIs as an actionable link, regardless of whether they know about DOIs.
>   -  Users who do not know how to right-click on the link and choose “Copy Link”, will still be able to easily copy the DOI URL.
>   -  Machines and programs (e.g. bots, etc.) will recognize the DOI as a link, thereby increasing discoverability and usage.
>

**Comment by bgruening** [comment]
@stain thanks for putting all this in context and adding references. I think this is exactly what we are doing currently and we can close this issue as well. Let's add more identifiers as we go.
