### ISSUE TITLE
Python 3.6 and bioconda-utils

### ISSUE THREAD

**Issue by micknudsen** [bioconda/bioconda-utils#254]
The `bioconda-utils` package is not compatible with Python 3.6, which is the default Python version shipping with Anaconda. Since `bioconda-utils` must be installed in the root environment, it is rather complicated to run. Are there any plans to make a Python 3.6 version?

```
$ conda install bioconda-utils
Fetching package metadata ...............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - bioconda-utils -> python 3.5*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by daler** [comment]
Yes, there are plans for 3.6, but the setup for bioconda includes building a separate, isolated conda installation so you don't have to worry about touching your root env. See here:
https://bioconda.github.io/contribute-a-recipe.html#build-an-isolated-conda-installation-with-dependencies

**Comment by micknudsen** [comment]
Thanks! Somehow I completely missed the point of the isolated conda installation. It all makes sense now.
