### ISSUE TITLE
[latest] tag - quay.io - docker

### ISSUE THREAD

**Issue by klugem** [bioconda/bioconda-utils#271]
Is it possible to add and update a "latest" tag for docker containers on https://quay.io/repository/biocontainers/ whenever a new version of a recipe is build ?

**Comment by bgruening** [comment]
@klugem in theory yes, but strictly we do not know when a container is latest, as also old packages can be added. So this is a little bit tricky. So I thought the most save way is to leave the latest tag out of purpose.

**Comment by klugem** [comment]
Thanks for the fast reply. :) I see your point but shouldn't contain an updated version of an recipe a newer version of the software in most cases?

I ask because I find it inconvenient to look up the available versions of the docker container in the repository before I can pull/run them.

**Comment by bgruening** [comment]
In most of cases yes but not in all :-(.
We provide tooling to retrieve the docker containers automatically. For example CWL and Galaxy are using galaxy-lib to do this. Happy to help you if you like.

**Comment by klugem** [comment]
Thanks for the offer to help. I found a solution that works for me. (pulling the latest version automatically and mirroring it on docker hub with "latest" tag)
