### ISSUE TITLE
Lint: about:summary should be 1 line

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-utils#275]
The `about:summary` field should contain just a single headline. The description goes into `about:description`. Enforcing this would e.g. allow showing the summary line in a tabular package listing. 

I suppose the length of a line is debatable. 80 characters?

**Comment by johanneskoester** [comment]
I think a few sentences are ok. I don't think there is an immediate need to constrain the lines. Do you have an example where this went wrong?

**Comment by epruesse** [comment]
I think it should be at most one sentence - the other sentences should go into `description`. 

We have two fields to work with, `summary` and `description`. As per conda docs, `summary` should be a one-line summary and `description` should contain a brief paragraph. An example where those are used well would be [mrbayes](https://bioconda.github.io/recipes/mrbayes/README.html).

In the end, I think we have just not been using `description` enough. It wasn't even rendered in the package readme until recently, so some people used the `notes` field instead. 

The utility of having both fields would probably come intuitive to most of us if they where called `title` and `abstract` instead. Whether it's software packages, papers, git commits, github issues or docstrings describing functions, classes or methods - having a short one-liner and a brief description is highly useful. The one liner makes listings, say search results, more informative, and the brief paragraph informs the decision to dig further.

Examples of rather long `summary` entries would be most of the bioconductor packages. The record holder is [`bioconductor-rcas`](https://bioconda.github.io/recipes/bioconductor-rcas/README.html
) with over 1.5kB. But there are  plenty others, [`meraculous`](https://bioconda.github.io/recipes/meraculous/README.html) for example.

**Comment by epruesse** [comment]
Here is another good reason: The `anaconda.org/bioconda/<package>` page looks weird when the summary gets long, and it will always show the `description` part in an actually more prominent pane at the bottom.
