### ISSUE TITLE
Fail with lint if blacklisted recipe is tried to be updated.

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-utils#280]
If a recipe is blacklisted and somebody updates it, all tests silently pass because the recipe is ignored. It would be better if linting failed in such a case, with an instruction to remove the recipe from the blacklist.
@mbargull please put this on your todos for the next weeks.

**Comment by mbargull** [comment]
Hm, so this would mean the linter would complain even when a recipe is changed and simultaneously put on the blacklist, right? Maybe we should then let the "fix" message for such a `blacklisted` lint function explicitly point at being able to use `[skip lint blacklisted for <recipe name>]` in the commit message.

**Comment by johanneskoester** [comment]
Yes, that makes sense.

**Comment by epruesse** [comment]
It would only trigger if the buildno/version of the recipe is changing and it goes on the blacklist. That's not good anyway. No package for that change. Any reason we need to do that ever?

**Comment by dpryan79** [comment]
That only happens accidentally.
