### ISSUE TITLE
Conda-Build 3 support

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-utils#284]
1. [x] Update pinning to conda build 3
2. [x] Replace our env matrix by https://github.com/conda-forge/conda-forge-pinning-feedstock
3. [x] add test case for new `outputs:` feature of CB3 meta.yaml
----
3. [ ] update docs to include the new compiler polices
4. [ ] adopting rules to include noarch packages
----
5. [x] point out `host:`/`build:` section differences in docs
6. [ ] Adjust/add lint functions
   1. [ ] replace `build:` by `host:` when applicable
   2. [ ] replace `build: [gcc]` by `build: {{ compiler("c") }}` or `build: {{ compiler("cxx") }}`
   3. [ ] allow `source:` to be a list (@bgruening: I assume `cargo-port` will need similar adjustments)
   5. [ ] in the docs and the lint explanation, explain how to use the new compilers with the old ABI if necessary (e.g. to stay compatible with conda-forge that might be slower in rebuilding with the new compilers).
   6. [ ] prohibit `fn:` in `source:`, now redundant if `url:` points to file (which it really should)

**Comment by bgruening** [comment]
I added two other points, feel free to remove them.

**Comment by mbargull** [comment]
Sorry for the delay. Added some more points. Will get this done in the next days.

**Comment by kyleabeauchamp** [comment]
I made a PR with a prototype BWA recipe upgraded for CB3:

https://github.com/bioconda/bioconda-recipes/pull/8737

**Comment by kyleabeauchamp** [comment]
Then there's the question of how to go about updating the pins (e.g., do we recommend that authors manually change the pins at their convenience and increment the build number).

**Comment by epruesse** [comment]
CB3 seems to work :)
