### ISSUE TITLE
config.yml file for bioconductor-skeleton

### ISSUE THREAD

**Issue by cramjaco** [bioconda/bioconda-utils#299]
Please forgive me if this is an ignorant question, but I'm having trouble figuring out where to learn more about this online. Perhaps somebody can point me in the right direction.  I am trying to download bioocondutor skeleton files as described here https://bioconda.github.io/guidelines.html. I've installed bioconda utils, and then ran in an arbitrary directory

`bioconda-utils bioconductor-skeleton recipes config.yml DESeq2`

bioconda then yells that there is 
>`No such file or directory: 'config.yml'`. 

I have found any number of config.yml examples online, but I'm not sure where this file is supposed to come from, or what it is supposed to say. Could somebody point me to a good resource for correctly downloading a bioconda skeleton file and setting up `config.yml`? Thanks for your consideration.

**Comment by daler** [comment]
@cramjaco after installing bioconda-utils, the trick is to run that command in a clone of the [bioconda-recipes](https://github.com/bioconda/bioconda-recipes) repository. In there is the `config.yml` and the `recipes` directory in which the new bioconductor recipes will be written.

However, please be aware that if you're intending on updating a package to Bioconductor 3.7, it will have to wait (see some discussion [here](https://github.com/bioconda/bioconda-recipes/pull/8925#issuecomment-389660854)).  Adding a new package from BioC 3.6 should be fine though.

**Comment by nick-youngblut** [comment]
It would be *really* helpful to include this in the docs. I couldn't find anything in the bioconda docs about where the `config.yml` file is or what's supposed to be in it.
