### ISSUE TITLE
Biconda-utils/utils.py get_recipes does not support deep nested recipes

### ISSUE THREAD

**Issue by mikecormier** [bioconda/bioconda-utils#307]
The get_recipes in bioconda-utils/utils.py only supports two levels of nesting. Our application, and other potential applications, are not supported under this model. Would it be possible to implement a dynamic file nesting check for get_recipes so that any recipes that have deeper nesting are included in the build?

**Comment by daler** [comment]
Sure -- a PR for this would be more than welcome! Keep in mind though we're in the middle of a big overhaul to support conda-build 3. It might be best if you base your PR off of the `cb3-migration` branch, or alternatively wait until that branch is merged into master.

**Comment by mikecormier** [comment]
Thanks for the reply. I will put a PR together on the `cb3-migration` branch. When do you expect to merge `cb3-migration` into master?

**Comment by daler** [comment]
We're working on https://github.com/bioconda/bioconda-recipes/pull/9049 and https://github.com/bioconda/bioconda-recipes/pull/9041, both of which are configured to use the `cb3-migration` branch instead of master. Lots of work to do. A couple weeks maybe?

If you need it sooner than that, then a PR targeting master branch might be a better option for you.

**Comment by johanneskoester** [comment]
@mikecormier we can merge your PR into the cb3-migration branch once tests pass. Then, you can simply use that branch for GGD, until it is merged into master.

**Comment by johanneskoester** [comment]
Here you see how you can install a python package like bioconda-utils from a git branch: https://stackoverflow.com/a/20101940/7070491

**Comment by mikecormier** [comment]
Hi @johanneskoester,
That sounds great. I am currently adding a test for the new get_recipes to test for different levels of nested recipes. My current commit to bioconda-utils/uilts.py passes all test except for 1. @daler mentioned that this test has been failing with the cb3-migration and is not due to the changes I made. 

I have been getting errors when I install biconda-utils from the both the master and cb3-migration branches. At this point I have been using` conda install -c bioconda -c conda-forge bioconda-utils` to install bioconda-utils, but once my PR is merge I can try to install with the cb3-migration branch again.

**Comment by epruesse** [comment]
Has been fixed
