### ISSUE TITLE
linting fn is too strict

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-utils#316]
> 1	recipes/r-bipartite	should_not_use_fn	{'should_not_use_fn': True, 'fix': 'URL should specify path to file, which will be used as the filename'}		URL should specify path to file, which will be used as the filename	True

What was the intend of this change? I think we need fn in R packages, or to be more precise in all packages that do have multiple URLs.

Can we disable that or check for a list or URLs?

**Comment by bgruening** [comment]
ping @mbargull @daler

**Comment by mbargull** [comment]
Sorry I didn't reply before, I'm still lacking behind on a **ton** of issues...
I [fixed](https://github.com/conda/conda-build/pull/3021) that in `conda-build` a few days before you posted this issue :smile:.
The updates from gh-324 should take care of this!

**Comment by epruesse** [comment]
Closing - we have only very few recipes with `fn:` and most seem to be indeed unnecessary.
