### ISSUE TITLE
Make `bioconda_utils-conda_build_config.yaml` an `exclusive-config-file`

### ISSUE THREAD

**Issue by mbargull** [bioconda/bioconda-utils#325]
We need to take advantage of https://github.com/conda/conda-build/pull/3022 and specify our `bioconda_utils-conda_build_config.yaml` also as an `exclusive-config-file`. Reason:
> The use case is Bioconda which is essentially a conda-forge downstream repository now. As such we want to use conda-forge-pinning's conda_build_config.yaml but also add our own on top of that. Using --variant-files won't work, due to the config file processing order, as soon as we would start to add per-recipe configuration files.

**Comment by epruesse** [comment]
@mbargull What's the difference between the config files? Will you be able to fix this?

**Comment by mbargull** [comment]
Sorry, forgot about this one. The fix is trivial and in gh-591.
The difference between the "variant" and "exclusive" config files is their precedence.
We have:
variant config files
*take precedence over*
`recipe/conda_build_config.yaml` which
*takes precedence over*
exclusive config files.
Meaning, you can't override the variant config files, i.e., our `bioconda_utils-conda_build_config.yaml`, for a single recipe, e.g., won't be able to prevent building against `htslib: 1.9` (via the recipe's config file -- in `meta.yaml` still possible, of course).
