### ISSUE TITLE
Add link to cargo-port source to package docs

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-utils#332]
The documentation should add a generated link to the backed-up source code on `cargo-port`.

ping @bgruening Can you provide a bit of code that generates the link? You're more familiar with `cargo-port`...

**Comment by bgruening** [comment]
With documentation you mean the tool card, like here? https://bioconda.github.io/recipes/abeona/README.html

**Comment by epruesse** [comment]
@bgruening Yep

**Comment by epruesse** [comment]
This would be best fixed by fixing #21
