### ISSUE TITLE
Monitor upstream projects for new releases

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-utils#345]
I can't find a current ticket on this, so opening a new one. 

## Summary
As Bioconda scales to more and more packages, keeping everything up to date manually is becoming challenging.  Matching the approach taken by other software distributions we should have a mechanism that monitors upstream projects for new releases and creates PRs automatically.

ping @corburn @daler @johanneskoester @bgruening - comments?

#### Bioconda:
 - bioconda/bioconda-recipes#5554
 - #178  -- https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/pypi.py
#### Debian:
 - https://wiki.debian.org/debian/watch
 - https://manpages.debian.org/stretch/devscripts/uscan.1.en.html
 - https://github.com/Debian/devscripts/blob/master/scripts/uscan.pl

#### Conda-Forge:
 - https://github.com/regro/cf-scripts

#### Other
 - https://libraries.io

## Plan

The concept is obvious: for each package, determine if there is a new upstream release, and if so create a branch/PR updating the meta.yaml accordingly. The devil will be in the detail, as usual. 

### 1. Iterate over packages

Docs already does it so this, as does `pypi-check` (doesn't work for me though).

### 2. Scan

The Debian tool `uscan` does exactly what we want - it's Perl though and doesn't integrate as neatly with Conda as a Python thingy could.  Still, it shows that a web scraper solution with some regexps to customize parsing will work for most situations, so we don't have to go down the API route with implementations for every hosting site.

 - built-in patterns for typical hosting sites
 - alternate patterns configurable via `meta.extra.watch`
 - exclude package via `meta.extra.watch.disable=True`
 - handle multi-url packages

###  3. Bump PR

 - Multi-Update-PRs vs Single-Update-PRs
   - Per-updated-package branches and PRs are likely easier to manage than big multi-update PRs. That way each update can be tested and merged or revised individually. 
 - Clutter avoidance
  - Run in a fork bioconda/bioconda-recipe-updates (GH staff can create that for us)
  - Branch-per-package (re-usable)
  - Bump existing PRs if upstream pushes a new release faster than we can merge

The whole thing can then easily run in a circleci cron job.

**Comment by kyleabeauchamp** [comment]
I would vote for any approach that shares effort with conda-forge, as we're in this together for better or worse.

**Comment by epruesse** [comment]
@kyleabeauchamp I don't know how feasible that is. As far as I've understood their code, it's pivoting a lot around the concept of feedstocks.

**Comment by daler** [comment]
@epruesse it took me a bit to find it, but https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/update_upstream_versions.py has functions for GitHub, LibrariesIO, NPM, and PyPI. 

We definitely need one for Bioconductor in there, maybe for Rust cargo too. `uscan` might have some ideas that could improve that module, but I haven't looked closely at that.

Given how much of cf-scripts is feedstock managment overhead, it may be that this module is the only code can re-use from that repo, but at least we can share effort with them in the version-scraping department.

**Comment by epruesse** [comment]
@bgruening I think the task of rebuilding packages if upstream packages have been bumped can be handled separately. If CB3 pinings work correctly, the hash changes, so no new build number is required.

**Comment by bgruening** [comment]
>  I thought about working from there, but the license is unclear to me.

They will clarify this :) --> https://gitter.im/conda-forge/conda-forge.github.io

> If CB3 pinings work correctly, the hash changes, so no new build number is required.

I'm not sure about this one. I think the entire community is bumping even if only the pinning have changed. Probably good to double check this.

**Comment by epruesse** [comment]
@bgruening When I bumped blast 2.7.1 to rebuild with boost 1.67 the sub-recipe for blast 2.6.0 was also rebuilt. So mostly it triggering the CI. That’s why I figure those can be dealt with on cron. 

Elmar

--
message sent from mobile device

**Comment by epruesse** [comment]
Also - could you ask GH staff to create a fork  of Bioconda-recipes within Bioconda org? They can do that AFAIK, but there is no interface. Would help keeping the main repo clean. 

Elmar

--
message sent from mobile device

**Comment by epruesse** [comment]
closing in favor of #354
