### ISSUE TITLE
Run `conda build purge` last?

### ISSUE THREAD

**Issue by dpryan79** [bioconda/bioconda-utils#346]
I noticed that `conda build purge` is run after every build/upload. That's fine in an interactive environment, but I've noticed that on the `bulk` branch it occasionally results in build time outs. This is due to nothing being printed to screen for 10+ minutes. That usually only happens if a package takes 15-20 minutes to build, so most packages won't trigger this. Moving `conda build purge` to the very end (after the success/fail statistics are printed) will both make builds quicker and prevent this behavior. The downside is obviously that a lot of disk space can get wasted. I'm happy to make a PR implementing the change, but given the change in disk space usage it'd be nice to get some input first.

**Comment by dpryan79** [comment]
This is the line that would get moved: https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/build.py#L477

**Comment by epruesse** [comment]
If this is still current, just do it. If we run into disk space issues, we can always fix that later by monitoring disk space between builds and running purge if necessary. If we don't ... well, don't bother.

**Comment by dpryan79** [comment]
not really an issue any more
