### ISSUE TITLE
Lint: local testing `TypeError` in `utils.RepoData(cache)`

### ISSUE THREAD

**Issue by dlaehnemann** [bioconda/bioconda-utils#375]
When trying to test locally with the setup described in the [Contributing a recipe docs](https://bioconda.github.io/contribute-a-recipe.html#test-locally), I get the same error upon linting in both the [circleci client method](https://bioconda.github.io/contribute-a-recipe.html#circle-ci-client-method) and the [bootstrap method](https://bioconda.github.io/contribute-a-recipe.html#bootstrap-method). For the latter, this occurs when running `bioconda-utils lint recipes config.yml --git-range master`. I have verified this on two different computers and for two completely different recipes, so I'm assuming this is a linter bug. However, it does not occur in the online circleci testing. Here's the traceback:

```
Traceback (most recent call last):
  File "/tmp/miniconda/miniconda/bin/bioconda- utils", line 11, in <module>
    sys.exit(main())
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 695, in main
    bioconductor_skeleton, clean_cran_skeleton, autobump
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 228, in lint
    utils.RepoData(cache)
TypeError: __new__() takes 1 positional argument but 2 were given
```

@bioconda/build-system: Any idea where this is coming from? Any clues how to fix this?

**Comment by SchwarzMarek** [comment]
Hi,
I have same problem with my local circleci install. I've used snap to install circleci and docker in case it is relevant. Any advice?

**Comment by daler** [comment]
ping @epruesse (I only just now added you to bioconda/build-system)

**Comment by dlaehnemann** [comment]
@SchwarzMarek
If you just want to get on with testing locally (to reduce the circleci job load online created by pushes to the repo), you can use the [bootstrap method](https://bioconda.github.io/contribute-a-recipe.html#bootstrap-method) and just skip the `# optional linting` command. Everything else should run normally.
And another fallback solution would be to just push your new branch to the repo and let the tests run on circleci.com -- the error does not occur there, for some reason.

**Comment by epruesse** [comment]
Sorry guys - I added that bug when I made RepoData a singleton. I guess I should have spent more time on unit tests... :(

**Comment by dlaehnemann** [comment]
Glad it's so easily fixed and cheers for the forward and the quick response!
