### ISSUE TITLE
Unable to rebuild old recipe

### ISSUE THREAD

**Issue by pb-cdunn** [bioconda/bioconda-utils#391]
After #383, we are no longer able to re-build `pb-falcon` (used by `pb-assembly`), so our entire suite of PacBio assembly software is adrift.

See several builds on various small changes and some discussion at:
* https://github.com/bioconda/bioconda-recipes/pull/13085

**Comment by dpryan79** [comment]
Hmm, adding `conda-forge/label/cf201901` to the channels would fix this too.

**Comment by pb-cdunn** [comment]
Worked last night. Thanks.
