### ISSUE TITLE
 Incorrect links on recipe pages

### ISSUE THREAD

**Issue by apeltzer** [bioconda/bioconda-utils#402]
https://github.com/bioconda/bioconda-recipes/issues/13426

Im a bit lazy, so closing the other issue and opening here 👍

**Comment by epruesse** [comment]
From original issue: 
<img width="727" alt="bildschirmfoto 2019-01-31 um 15 41 05" src="https://user-images.githubusercontent.com/2359510/52061486-b4b67f00-256e-11e9-93c4-876abb622741.png">

**Comment by epruesse** [comment]
@apeltzer That was my bad. I'll look into it today.
