### ISSUE TITLE
`bioconda-utils autobump` vs `bioconda-utils update`

### ISSUE THREAD

**Issue by dpryan79** [bioconda/bioconda-utils#409]
The documentation for [updating a recipe](https://bioconda.github.io/contribute-a-recipe.html#updating-recipes) (or more fully [here](https://bioconda.github.io/updating.html) mentions using `bioconda-utils update`. As best I can tell that never actually existed. It seems that that was renamed to `bioconda-utils autobump` at some point. If that's correct, we should either update the documentation or change the function name to match what the documentation says.

Ping @daler and @epruesse

**Comment by epruesse** [comment]
It used to be `update`, but since that was a little too generic (and potentially misleading). Having gotten used to the term `autobump` I had picked as the label to tag the generated PRs, I renamed the command to match.

And then I didn't update the docs. So it's on me.

**Comment by epruesse** [comment]
BTW: I'd love some feedback on #408 - do we have anyone good with the design aspects?

**Comment by epruesse** [comment]
Please vote on this comment on how to resolve this:
 - :+1: if you think we should rename the command to `bioconda-build update`
 - :-1: if you think we should update the docs to reflect the current name `autobump`

**Comment by epruesse** [comment]
Everything set to autobump for now. Just because update is a stop word that's hard to find.
