### ISSUE TITLE
Unable to update conda in bioconda/bioconda-utils-build-env:latest

### ISSUE THREAD

**Issue by thermokarst** [bioconda/bioconda-utils#411]
The current docker image for `bioconda-utils-build-env` is in an "un-upgradable" state:

```bash
docker run -it bioconda/bioconda-utils-build-env:latest /bin/bash
[root@0989ac05cd0b /] conda update conda
Solving environment: failed

CondaUpgradeError: This environment has previously been operated on by a conda version that's newer
than the conda currently being used. A newer version of conda is required.
  target environment location: /opt/conda
  current conda version: 4.5.11
  minimum conda version: 4.6
```

This issue has been detailed on the conda mailing list:
https://groups.google.com/a/continuum.io/forum/#!topic/conda/GbVfDSL8eU8

This issue was observed in:

```bash
docker images bioconda/bioconda-utils-build-env --digests
REPOSITORY                          TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
bioconda/bioconda-utils-build-env   docs_update         sha256:7cdfe29f9cd64be54d0af61035910821828d061b0f9f468e755d800863097bd8   18d79076f049        33 hours ago        2.59GB
bioconda/bioconda-utils-build-env   latest              sha256:b53f65dd778a9bbd1721e9c830bbbcadeff5286fd24bb8c4598d66dd81d54095   7cd9397b8002        44 hours ago        2.59GB
```

I double-checked `condaforge/linux-anvil-comp7:latest` - they pushed out a build in the last 24 hours that doesn't suffer from this problem, so maybe a rebuild using this base image is all we need 🤞

**Comment by epruesse** [comment]
ping @bgruening

**Comment by bgruening** [comment]
@thermokarst pleaes use `:2019-02-01` we swtiched to this one on master for the time being. Conda 4.6 seems to have some issues and as long as we do not switch to 4.6.x we will use this slightly older Docker image.
