### ISSUE TITLE
Don't download repodata needlessly

### ISSUE THREAD

**Issue by dpryan79** [bioconda/bioconda-utils#412]
I've noticed this with the nightly uploads that `bioconda-utils build` with no packages specified will download the repodata from bioconda/conda-forge for every recipe. This adds on about 5 seconds for each of the ~6000 packages we currently have. Since this equates to an extra ~10 hours per iteration through all of the packages we can't actually get through all of them.

This must be a recent change, it wasn't happening in December when we were building all of bioconductor in bulk.

**Comment by dpryan79** [comment]
This is because `check_recipe_skippable()` doesn't have any way to cache the results of `RepoData()`. It's an easy fix at least.

**Comment by epruesse** [comment]
There is also a bug in the `RepoData` class - it re-downloads every time it's reinstanciated. Fixed in docs_update branch...
