### ISSUE TITLE
github.io page not up to date ?!?

### ISSUE THREAD

**Issue by martin-raden** [bioconda/bioconda-utils#413]
Hi,

I found the content of the repo and the github.io pages differing.

namely the [guidelines at github.io](https://bioconda.github.io/bioconda-utils/guidelines.html) talks about `CONDA_BOOST` while the respective paragraph in the current version [at github](https://github.com/bioconda/bioconda-utils/blob/master/docs/source/guidelines.rst) does not mention it anymore..

maybe some general problem? or do I compare the wrong things?

thanks for clarification,
Martin

**Comment by epruesse** [comment]
@bioconda/core For some reason, Github is rendering bioconda/bioconda-utils:gh-pages instead of bioconda/bioconda.github.io. Can someone with permissions on the Org check what's going on?

**Comment by bgruening** [comment]
@martin-raden the problem is http://bioconda.github.io/bioconda-utils/ vs. http://bioconda.github.io/. The latter is the correct one.

**Comment by bgruening** [comment]
http://bioconda.github.io/bioconda-utils/ ist Geschichte!

**Comment by bgruening** [comment]
Thanks for reporting @martin-raden ... thanks @epruesse
