### ISSUE TITLE
Unit tests take veeerrrrry long

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-utils#420]
I'd appreciate if those most proficient in the respective tests (bioconductor_skeleton, ...) could have a look at whether the times could be improved a little. :)

For example, on #419, we used

test|time
----|----
autobump-test | 29:19
test-macos | 27:34
test-linux | 33:26
test-linux (long-running) | 22:57
build-docs | 15:10

- Autobump could be run on less than everything, if I can find a good, representative set of recipes. It's running on all so that "new" brokenness also turns up.
- Build-docs might benefit from threading.
- We could have all tests but build-docs return early true on changes affecting only `.rst` files

Particularly annoying are `test-linux` and `test-macos` though, as the long duration makes it tough to run `pytest` locally. Here's a combined list of the culprits, sorted by average time as printed by pytest:

module |  test | stage | macos | linux
---|---|---|---|---
test_bioconductor_skeleton.py | test_experiment_data | call | 188.6 | 144.44
test_utils.py | test_nested_recipes | call | 172.21 | 112.36
test_utils.py | test_single_build_only[with docker] | setup |  | 256.07
test_utils.py | test_compiler | call | 158.31 | 67.95
test_utils.py | test_cb3_outputs | call | 122.78 | 81.91
test_bioconductor_skeleton.py | test_meta_contents | call | 102.49 | 86.52
test_utils.py | test_docker_builder_build | call |  | 146.97
test_bioconductor_skeleton.py | test_overwrite | call | 75.39 | 55.37
test_utils.py | test_docker_build_fails | call |  | 129.92
test_bioconductor_skeleton.py | test_bioc_write_recipe_skip_in_condaforge | call | 59.98 | 46.02
test_bioconductor_skeleton.py | test_bioc_write_recipe_no_skipping | call | 60.33 | 44.96
test_bioconductor_skeleton.py | test_annotation_data | call | 58.54 | 24.25
test_bioconductor_skeleton.py | test_pkg_version | call | 47.0 | 35.7
test_utils.py | test_docker_build_image_fails | call |  | 77.55
test_pkg_test.py | test_pkg_test_conda_image | call |  | 73.62
test_pkg_test.py | test_pkg_test | call |  | 73.23
test_pkg_test.py | test_pkg_test_custom_base_image | call |  | 72.68
test_utils.py | test_build_empty_extra_container | call |  | 69.34
test_utils.py | test_single_build_with_post_test[with docker] | call |  | 62.16
test_utils.py | test_single_build_with_post_test[system conda] | call |  | 62.05
test_utils.py | test_skip_dependencies | call | 33.4 | 22.41
test_bioconductor_skeleton.py | test_nonexistent_pkg | call | 28.89 | 25.5
test_utils.py | test_conda_as_dep | call | 25.98 | 20.09
test_utils.py | test_multi_build[system conda] | setup | 40.07 |
test_bioconductor_skeleton.py | test_bioarchive_exists | call | 21.43 | 15.81
test_bioconductor_skeleton.py | test_find_best_bioc_version | call | 9.31 | 22.14
test_utils.py | test_upload | setup | 12.64 | 11.87
test_utils.py | test_conda_forge_pins | call | 13.86 | 9.53
test_utils.py | test_bioconda_pins | call | 13.03 | 9.83
test_utils.py | test_conda_purge_cleans_up | call | 12.22 | 10.44
test_utils.py | test_env_sandboxing | call | 13.38 | 9.14
test_utils.py | test_single_build_only[system conda] | setup | 12.07 | 9.86
test_utils.py | test_rendering_sandboxing | call | 11.81 | 9.01
test_utils.py | test_upload | call | 10.89 | 9.01
test_utils.py | test_nested_recipes | teardown | 9.56 | 4.44
test_pkg_test.py | test_pkg_test_mulled_build_error | call |  | 12.93
test_bioconductor_skeleton.py | test_bioarchive_exists_but_not_bioconductor | call | 1.31 | 7.26
test_utils.py | test_built_package_paths | call | 4.92 | 2.51
test_bioconductor_skeleton.py | test_cran_write_recipe | call | 3.38 | 3.21
test_bioconductor_skeleton.py | test_cran_write_recipe_no_windows | call | 2.93 | 2.32
test_utils.py | test_variants | call | 2.6 | 1.72
test_linting.py | test_setup_py_install_args | call | 2.29 | 1.56
test_linting.py | test_uses_javajdk | call | 1.9 | 1.38
test_linting.py | test_uses_perl_threaded | call | 1.86 | 1.39
test_linting.py | test_missing_hash | call | 1.55 | 1.16
test_linting.py | test_should_use_compilers | call | 1.42 | 0.93
test_linting.py | test_missing_tests | call | 1.33 | 0.95
test_linting.py | test_uses_git_url | call | 1.26 | 0.96
test_linting.py | test_should_not_be_noarch | call | 1.26 | 0.95
test_linting.py | test_lint_skip_in_recipe | call | 1.45 | 0.67
test_linting.py | test_compilers_must_be_in_build | call | 1.3 | 0.75
test_linting.py | test_invalid_identifiers | call | 1.03 | 0.76
test_linting.py | test_missing_summary | call | 0.84 | 0.58
test_linting.py | test_missing_license | call | 0.81 | 0.57
test_linting.py | test_uses_setuptools | call | 0.79 | 0.58
test_linting.py | test_has_windows_bat_file | call | 0.79 | 0.57
test_linting.py | test_should_not_use_fn | call | 0.78 | 0.58
test_linting.py | test_missing_home | call | 0.75 | 0.57
test_linting.py | test_deprecated_numpy_spec | call | 0.65 | 0.5
test_utils.py | test_get_deps | call | 0.41 | 0.27
test_linting.py | test_empty_build_section | call | 0.27 | 0.2
test_utils.py | test_load_meta_skipping | call | 0.13 | 0.1
test_utils.py | TestSubdags::test_subdags_out_of_range | call | 0.01 | 0.01
test_utils.py | TestSubdags::test_subdags_more_than_recipes | call | 0.01 | 0.01

**Comment by dpryan79** [comment]
I'll look into caching the bioconductor package list, since downloading and parsing it again and again in the tests is probably eating up half the time (it takes 30+ seconds).

**Comment by epruesse** [comment]
@dpryan79 Thx!

**Comment by dpryan79** [comment]
See https://github.com/bioconda/bioconda-utils/pull/421 , which is a PR on this PR. It trims about 3 minutes off the bioconductor tests when I compare things locally. Note that at least on OSX the first ~8 minutes are needed for ~80% of the tests, it's `test/test_utils.py` that requires the majority of the time.

**Comment by epruesse** [comment]
merged #421 to #417

**Comment by epruesse** [comment]
Most of the time goes down for calling `build` and `render`. Not much to be done about it - conda is just that slow.
