### ISSUE TITLE
Combine update-pinings with autobump

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-utils#423]
I'm picturing about this:
 - iterate over recipes in topo order, starting at ancestors
 - check if they need version-bump OR just pinning-rebuild
 - skip descendants of recipes for which PRs exist
   - mark the recipes blocking other bumps

So if I see this right, I need to change the way recipes are iterated. Instead of random shuffle, I'll go by the graph, which means pre-loading all recipes. This creates some questions re handling of recipes with updates in progress. I think using the putative, new state of the recipes is the right way, although I don't see actually possible situations in which it would make a difference.

Do we stick to the bulk-approach for "doing migrations" (I think that's CF lingo for updating pinnings), or do we come up with an iterative way of doing this with individual builds and a special label to keep packages in until the update is complete?

**Comment by epruesse** [comment]
@dpryan79 - is merging the two commands OK to you? On the cli, I'd add `--update` with `pinning`, `version`, `both` as options I think, and merge the other options.

Internally, I'd turn `update_pinning.py` into a `Filter` for the pipeline that makes the version number bump as needed.

It'll be slower, probably, but it's going to be easier to run this, at least right now. I can then have autobump create PRs in stages, so that we gradually move through the backlog of packages that need the gcc7 rebuild.

**Comment by dpryan79** [comment]
@epruesse Merging the two commands (maybe just call it `update` rather than `autobump`) is certainly OK. I had initially thought of just adding a flag to `autobump` to update the pinnings, but it was doing enough other stuff that it was quicker to just write something else. Merging the two would be much nicer long-term though :)

**Comment by dpryan79** [comment]
BTW, the last time I looked there was one loop in the DAG, which prevented topological sorting (three perl packages with circular dependencies on each other).

**Comment by epruesse** [comment]
I think I saw those. There is one that includes itself, too. Might go away if we build the graph without the `run` deps. I don't see why we'd need to include those in the graph deps for building.

**Comment by epruesse** [comment]
I used the term `autobump` as label. `bump` and `update` seemed too generic. And then decided that using the same term in the cli made it easier to distinguish. We can change the command name any time though - don't think anyone is using `bioconda-utils` programmatically. Besides us, that is.

**Comment by druvus** [comment]
@dpryan79 @epruesse do you remember which three perl packages that are causing the loop? I was thinking of taking a look at them.

**Comment by dpryan79** [comment]
- perl-file-temp (requires perl-file-path)
 - perl-file-path (requires perl-test-simple)
 - perl-test-simple (requires perl-file-temp)

**Comment by epruesse** [comment]
IIRC it was just our packages actually. CPAN manages package dependencies in quite a bit of detail -- I doubt they allow circular deps.

**Comment by druvus** [comment]
It seems to be even worse mess than I first though with perl. 

I decided to look into dependencies defined at CPAN. Perl split their dependencies into three levels: build_requires, configure_requires and requires. However starting clean building a dependency graph based on ExtUtils::MakeMaker creates three loops. Two of them are between perl-extutils-makemaker to perl-data-dumper and perl-encode. The third is between perl-carp and perl-exporter. 

It seems that most linux distributions are using bootstrappping solve those circular dependencies, see for example this post about [Fedora](https://mmaslano.livejournal.com/11010.html). I guess we need to come up with a similar approach to rebuild all of them at conda-forge. 

I am not an active perl user so I don't know how the cpan installer solves it.

**Comment by epruesse** [comment]
One approach might be to just add those base things to a core perl package I suppose.

What tools did you use? Did you build the graph just on build_requires or on both build_requires and configure_requires or on requires as well?
