### ISSUE TITLE
Bot command wishlist

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-utils#424]
@bioconda/core Please add the commands you picture and what they should do. Or, if not commands, things it should do on events (like PR open) immediately.

**Comment by dpryan79** [comment]
An `autobump` command would be nice, so we don't have to run it on the command line. Something like:

    @ bioconda-bot autobump package1 package2 package3

Given how many packages could get affected, perhaps we should have an "autobump-preview", where it posts a list of what would be bumped.

**Comment by epruesse** [comment]
Hmm. That would then create new PRs, right?

**Comment by epruesse** [comment]
Or should it create a single pr?

**Comment by dpryan79** [comment]
A single PR would be preferable.

**Comment by epruesse** [comment]
So in principle, `@bioconda-bot lint` works now. *BUT* the use of pandas poses a problem on Heroku: the affordable dynos all have just 512MB available, and python with pandas loaded alone seems to occupy some 200MB of that. The Repodata dataframe needs some 100MB on top of that. This leaves very little room to actually do work.

**Comment by epruesse** [comment]
If anyone has further ideas or wishes - just open an individual issue.
