### ISSUE TITLE
async is a reserved keyword in python 3.7

### ISSUE THREAD

**Issue by sndrtj** [bioconda/bioconda-utils#428]
Hello,

In python 3.7, `async` and `await` are reserved keywords, and thus cannot be used as module names. On python 3.7, this means  `bioconda_utils/async.py` is unfortunately unimportable, and attempting to do so raises a `SyntaxError`. 

I would propose `async.py` gets renamed to `asynchronous.py` to resolve this issue. What do you think?

**Comment by bgruening** [comment]
Sounds good to me!
@sndrtj thanks for working on this!

**Comment by epruesse** [comment]
Fixed
