### ISSUE TITLE
Enforce recipe format

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-utils#440]
See #187 

Should we enforce a structure for `meta.yaml`s beyond its parsed content, and what should that structure look like?

Thinks we could check / enforce / correct (incomplete):

 - indentation levels
 - section order (CF does this)
 - use of jinja templates
 
Although I'm not certain we really need this, at least some of those rules would not be hard to do. In the end, we could just have a function that normalized the recipe format. The linter can check if it's different and issue a fail, and the bot can use the same function to offer a reformat. (Automatic probably not desirable as it will confuse users if something makes commits to their PR unexpectedly).

Votes? Close this or keep it on the list?

**Comment by dpryan79** [comment]
I fear this is just going to cause more work than it saves, unless recipes are breaking the autobump stuff otherwise.

**Comment by epruesse** [comment]
Agreed.

Please re-open this if you think we need to keep this at least on the wish list (or are ready to prepare a PR). Until then I'm closing because of `bigger fish to fry`.
