### ISSUE TITLE
Add Bioconda logo to anaconda.org account

### ISSUE THREAD

**Issue by peterjc** [bioconda/bioconda-utils#443]
I could't see a better place to open this issue, which is not really about the webpage but the wider internet footprint of the project.

Some projects have a nice icon on their anaconda page, e.g.

https://anaconda.org/r
https://anaconda.org/anaconda
https://anaconda.org/spyder-ide

Others have a default randomly generated image.

https://anaconda.org/bioconda

Can someone upload the BioConda logo to Gravatar for whatever email address is associated with the anaconda.org account?

**Comment by epruesse** [comment]
Should be quick fix - just needs someone with the right privileges :)

**Comment by dpryan79** [comment]
Hmm, I just looked and can't see how the image is set. It looks like it's from gravatar and the org is using Johannes' email address, so maybe it's the image associated with that?

**Comment by dpryan79** [comment]
Yeah, this is documented. Maybe it makes sense to create an email address that goes to all core members? We can then set the gravatar image to that and switch that to the primary email address.

**Comment by bgruening** [comment]
Uha we are getting professional? https://anaconda.org/bioconda

**Comment by bgruening** [comment]
@dpryan79 mailinglist? GoogleGroups?

**Comment by dpryan79** [comment]
Either one, though honestly your current solution should work :P

**Comment by bgruening** [comment]
Ok, closing this then now. @peterjc thanks for reporting!

**Comment by peterjc** [comment]
👍
