### ISSUE TITLE
cran_mirror no defined with conda skeleton cran template

### ISSUE THREAD

**Issue by nick-youngblut** [bioconda/bioconda-utils#445]
I'm working on creating my first recipe. I'm trying to start out with a R package with relatively simple dependencies: the `PACo` R package. I'm going through the documentation at https://bioconda.github.io/guidelines.html#guidelines, and I used `conda skeleton cran paco` as suggested for R packages on CRAN. At least with `conda build` v3.10.2, the "cran_mirror" variable in the `meta.yaml` template is not defined. For instance, the meta.yaml file that I generated contains:

```
  url:
    - {{ cran_mirror }}/src/contrib/paco_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/paco/paco_{{ version }}.tar.gz
```

... and running `circleci build` generates the following error:

```
Filtering 1 of 1 (100.0%) recipes/r-paco
Error: Failed to render jinja template in recipes/r-paco/meta.yaml:
'cran_mirror' is undefined
```

It would help to cover this issue in the bioconda docs on `conda skeleton cran` and what to do about it (eg., setting up a Jinja configuration or removing "cran_mirror" from the template). Should I just replace "cran_mirror" with a specific mirror (eg., https://cloud.r-project.org)?

**Comment by epruesse** [comment]
@nick-youngblut You probably figured this out by now - using `bioconda-utils build` or `circleci build` or just opening a PR and letting our CI do the job works.

**Comment by epruesse** [comment]
Ping @bgruening - since you seem to be looking into `circleci build` anyway at the moment- can you confirm this? What's the fix?

**Comment by bgruening** [comment]
This should be fixed for some time. @nick-youngblut please reopen if this is still a problem.
