### ISSUE TITLE
Channel Precedent in Installation Instructions

### ISSUE THREAD

**Issue by camillescott** [bioconda/bioconda-utils#447]
Hi all,

I noticed that the installation instructions have the user give precedent to the `conda-forge` channel over `defaults`, contrary to standard ana/miniconda installations; for me (and possibly others), this triggered the issue reported here: https://github.com/conda/conda/issues/6941

Is there a particular reason for this swap?

Cheers!

**Comment by dpryan79** [comment]
conda-forge should be first because it's the first place that all dependencies should be drawn from. In this case, conda-forge needed to update its package (or just remove it altogether). Few if any packages should be coming from `defaults` in a normal environment.
