### ISSUE TITLE
contributing guide references nonexistent `simulate-travis.py` script

### ISSUE THREAD

**Issue by 0xaf1f** [bioconda/bioconda-utils#448]
https://bioconda.github.io/contribute-a-recipe.html#build-an-isolated-conda-installation-with-dependencies

> In the top level of the bioconda-recipes repo, run:
> ```
> ./simulate-travis.py --bootstrap /tmp/miniconda --overwrite
> ```

But this script does not exist in bioconda-recipes, having been removed in https://github.com/bioconda/bioconda-recipes/commit/7b58564ceb7f361fa22bc1a42affb7dda60a6d6e. So an update in the documentation is warranted.

**Comment by epruesse** [comment]
Has been fixed
