### ISSUE TITLE
A few motivated edits to these docs

### ISSUE THREAD

**Issue by malcook** [bioconda/bioconda-utils#449]
Coming from the perspective of a new (wannabe) contributor...

 1. [Install conda and Docker \(one\-time setup\)](https://bioconda.github.io/contrib-setup.html#install-conda-and-docker-one-time-setup) should advise to `conda install conda-build`.  There is NO MENTION of `conda-build` in this site.  Failng to install it generates an `conda: error: argument command: invalid choice`, which is disheartening to the newb (me), despite the advice that appears at the end of the usage reminder, that `other commands, such as "conda build", are available when additional conda
packages (e.g. conda-build) are installed`.  It would be far better to advise the new contributor to install this package as part of contrib-setup.

 1. Until this https://github.com/conda/conda-build/issues/316  fixed, newbs to this project such as myself would really appreciate a warning to expect this in [Test locally](https://bioconda.github.io/contribute-a-recipe.html#test-locally) 

 1.  [One\-time setup](https://bioconda.github.io/contrib-setup.html) should advise to `cd bioconda-recipes`  prior to `git remote add upstream https://github.com/bioconda/bioconda-recipes.git`

All in favor?  Should I take the plunge?

**Comment by epruesse** [comment]
`1.` has been superceded in the mean time, `2.` doesn't seem to be noticed by many people anyway, `3.` will be fixed in #453
