### ISSUE TITLE
Meeting Monday April 8th, 9PM CEST 3PM EST

### ISSUE THREAD

**Issue by dpryan79** [bioconda/bioconda-utils#454]
- [ ] Shall we remove recipes that have been migrated to conda-forge (rather than just blacklisting them)? What about deprecated bioconductor packages or similar scenarios?
 - [ ] Procedure for adding new members. Keep the current pinned issue or should they ping us with their first PR?
 - [ ] more strict procedures to add new members
 - [ ] Position on CRAN (or other non-bioconductor) packages in bioconda: dissuade further submission in favor of conda-forge?
 - [ ] vote on #409: `bioconda-utils autobump` vs `bioconda-utils update`
 - [ ] Base perl packages: move to conda-forge? Who wants to maintain them?
 - [ ] Issues on bioconda-recipes: disable them?
 - [ ] bot updates
 - [ ] organising a Codefest
 - [ ] upcoming events
 - [ ] pinning updates, inform all of us about the new pinning strategy
 - [ ] Additions to the extended image (c.f. https://github.com/bioconda/bioconda-recipes/issues/13751 )

@bioconda/core: We sorely need another meeting. In preparation for that, please add any items that you think should be discussed here.

**Comment by epruesse** [comment]
ping @bioconda/core Please add yourself to this doodle poll: https://doodle.com/poll/tszceqd7gyyp8bqv

**Comment by dpryan79** [comment]
@chapmanb @druvus @jerowe @johanneskoester @mbargull @rvalieris @tomkinsc Please see the above agenda and doodle link.

**Comment by dpryan79** [comment]
@bioconda/core For those who can't make the meeting on Monday, please feel highly encouraged to post comments here about any of the agenda items that you have any strong opinions on. We'd obviously like input from as many people as possible :)

**Comment by tomkinsc** [comment]
When will the meeting be held? It's not obvious from the poll which time is the final one. It'll be on Gitter?

**Comment by dpryan79** [comment]
Since your entry we'll probably go for Monday at 9PM in Germany/3PM on the east coast. I'm really hoping another 1-2 people will add their availability, so that time could change a bit. We can use google hangout.

**Comment by dpryan79** [comment]
@tomkinsc We'll schedule for 9 PM in Europe/3 PM on the east coast. Someone (presumably me) will post a link in gitter for the google hangout.

**Comment by epruesse** [comment]
@bioconda/core If you cannot attend, please comment on the individual item issues I created or here to make your voice heard. If you cannot attend the meeting, please vote via github.

**Comment by jerowe** [comment]
I vote remove packages. It gets confusing having all kinds of packages all over the place. Some of my users put waaaaaaaaaay too much thought into which package they should have if they see it in two places.

**Comment by chapmanb** [comment]
Devon and Elmar -- thanks for organizing this. I left my thoughts on the separate issues and happy to work with whatever you decide. My schedule is pretty hectic right now so I can't make the call, and I appreciate your leadership on making this all happen.

**Comment by druvus** [comment]
I have been a little bit of lately due to admin stuff but I will try to join the call to be back on track.

**Comment by dpryan79** [comment]
The link to the google hangout is now in the core gitter channel.
