### ISSUE TITLE
Policy: recipe moved to CF or otherwise deprecated

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-utils#485]
From #454:
> Shall we remove recipes that have been migrated to conda-forge (rather than just blacklisting them)? What about deprecated bioconductor packages or similar scenarios?

We have a growing list of packages we no longer build for various reasons. They are currently marked in `build-fail-blacklist` and kept under `recipes/`.

**Comment by epruesse** [comment]
Option 1: Do nothing. We just keep going as is (for now).

**Comment by epruesse** [comment]
Option 2: Simply remove them from `/recipes` and `build-fail-blacklist`. Git history will allow tracking should we ever need to.

**Comment by tomkinsc** [comment]
I'd propose that we retain the recipes, but elsewhere: in a directory called "removed-recipes" or maybe a separate repo (along with removal of the entries from the blacklist file for either case). Keeping them in the git history preserves the information but it is not ideal for discovery.

**Comment by epruesse** [comment]
I'd say keeping a file that has the SHA of the deleting commit (or the one before that) and 
the name of the recipe meta.yaml could be useful.

So I made one: [deleted.txt](https://github.com/bioconda/bioconda-utils/files/3056335/deleted.txt)

It's a one liner to get that file:
```
git log --diff-filter=D --summary -- 'recipes/**/meta.yaml' | sed -n '/^commit/h; /^ delete.*yaml/ {G; s/ delete mode [^ ]* //; s/\ncommit//p}' | while read file sha; do [ ! -e $file ] && echo $sha $file; done | uniq -f 1
```

In summary, we've had 977 deleted `meta.yaml`s so far that were never recreated, and 539 of those were toplevel. Neither number is fully correct as some recipes didn't/don't have top level meta.yaml and I was too lazy to check for that.

**Comment by epruesse** [comment]
Consensus at the meeting was to delete at least those moved to CF. I think history parsing is simple enough (hey, a git repo is tiny compared to "normal" data for us). Should it turn out to be a problem, we can provide a script or recreate later.
