### ISSUE TITLE
Policy: joining Bioconda

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-utils#486]
From #454:
> Procedure for adding new members. Keep the current pinned issue or should they ping us with their first PR?

### How much do we expect of new members before they may join?

Also, please comment if you think a related topic, such as contribution guidelines, license to recipes, code of conduct, etc., should be on the agenda for the next meeting.

**Comment by epruesse** [comment]
### Option 1: Literally nothing. 

We are happy about everyone who will carry our badge. Intent to contribute is quite sufficient for becoming a member.

**Comment by epruesse** [comment]
### Option 2: At least a PR

Bioconda works because many people shoulder the burden of package maintenance together. We need commitment from our members, and we would like our members to know what that entails and for them to have demonstrated the ability to build a package.

**Comment by chapmanb** [comment]
My vote is for option 2. I want as many people to get involved as possible but it's also time for core members to approve and include people. Everyone can submit a working PR and then ping core members to merge and make them project members, and this might take away some of the initial overhead.

**Comment by druvus** [comment]
I also put my vote on option 2.

**Comment by tomkinsc** [comment]
I'd vote for an option somewhere between option 1 and option 2. Ease of contributing to bioconda is one of its main draws; I've heard from several people that they love the open and welcoming attitude of the community, and the feeling that anyone can contribute. I'd suggest retaining the ability to join without onerous onboarding, perhaps with tiered access. Permission to merge new PRs could be gated during the pull request process as an automated check. For example, if someone does not have N pull requests approved and merged already, they would need an explicit "OK" from a human reviewer before the check would pass. Additional user groups could be added to define scope of access with finer granularity than we have now.  Someone may have time to initially add a recipe for a package, but not to maintain it in perpetuity, especially if they move institutions, enter a new career stage, etc. Making it easy to become a "member" would allow contributors to feel it is OK to remain involved as they are available. (and of course designating oneself as the developer or maintainer would come with expectations of greater involvement). As an alternative to option 1, might be to have prospective members open a pull request with their username in a "users to add" file, which would demonstrate that the user is at least somewhat familiar with git.

I'd propose that we may want to consider having recipe linting also check for certain potentially risky changes in pull requests from new members that modify existing recipes: if a source URL is changed, maybe that should raise a flag until a user is "trusted", same with the appearance of a URL in a build script.

**Comment by epruesse** [comment]
We're using the PRs for people to request membership for now and requiring a review for every PR.
