### ISSUE TITLE
Policy: should we accept generic R packages (CRAN, etc)

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-utils#488]
From #454 
>Position on CRAN (or other non-bioconductor) packages in bioconda: dissuade further submission in favor of conda-forge?

**Comment by chapmanb** [comment]
My vote is for allowing these in bioconda. We should encourage recipes to go wherever people feel comfortable submitting and maintaining them.

**Comment by epruesse** [comment]
My vote is for disallowing them. Generic packages tend to be requisites for other non-life-science packages. Having them here creates trouble down the road and blurs the profile of Bioconda. The early necessity no longer exists, and with Bjoern as liaison on the CF side, getting packages merged from `staged-recipes` and turned into feed-stocks is not slower than merging them here.

At the very least, we should mark those packages as generic.

**Comment by janxkoci** [comment]
How about popular bioinformatic packages such as _seqinr_ or _ape_? They are not in bioconductor, but they are also not exactly "generic". See also e.g. these CRAN Task Views:

- [Phylogenetics](https://cran.r-project.org/web/views/Phylogenetics.html)
- [Genetics](https://cran.r-project.org/web/views/Genetics.html)

**Comment by dpryan79** [comment]
There's been some uncertainty about our decision on this, so we should discuss it in our next core meeting, which is on Monday.

**Comment by epruesse** [comment]
Decision finalized at todays meeting - R packages not requiring Bioconda packages are to be moved to conda-forge in all cases.

Added lint check in 4133fb25d94b714e7e3e277127bac2ff2f0b28e3 monitoring policy
