### ISSUE TITLE
Meeting Monday May 6th, 9PM CEST / 3PM EST

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-utils#494]
- [ ] Updates from the previous meeting
 - [ ] New bioconductor release, include the data packages?
 - [ ] Bot based upload to Anaconda ~~#508~~ #516 
 - [ ] Consider if/how to apply `repodata-patches` to the CDN-backed channel

 - [ ] Items on [meeting milestone](https://github.com/bioconda/bioconda-utils/milestone/2)

**Comment by dpryan79** [comment]
@bgruening I added an item onto the agenda for the next meeting regarding data packages for the next bioconductor release (scheduled for Tuesday I think). In short, do we really want to include them since the resulting containers are so large and most of them aren't actually changing? Since you're familiar with space constraints on the biocontainers side it'd be nice if you could weigh in.

**Comment by bgruening** [comment]
> New bioconductor release, include the data packages?

We do not have any space constraints on quay.io. But we are nice and don't want to be a burden to anyone. If possible we should avoid uploading data packages that do only have a different base R version. However, if there is a new genome-build we might want to upload one version?

> Bot based upload to Anaconda #508 #516

I do see the appeal here and I personally don't reall mind, but one of the reasons we still use public CIs and not a academic cloud to build artefacts is that we want to be completly transparent. As soon as we copy packages in the background we will loose some of this transparancy.

**Comment by epruesse** [comment]
>  As soon as we copy packages in the background we will loose some of this transparancy.

Can you elaborate? All it does is take the (public) artifact and image files and upload them to quay and anaconda. It's in a sense more transparent - you get to look at the packages beforehand, you can see when they get uploaded, things aren't hidden in them main commit log but visible from the PR.

I suppose we could use checksums to make it possible to verify that the exact same package that got built also gets uploaded. 

In terms of transparency, my biggest worry are actually the unknown sources that get downloaded during the package build.

**Comment by dpryan79** [comment]
I'll close this and pin an issue for the June meeting.
