### ISSUE TITLE
disable building a docker container at the start of every run

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-utils#495]
Currently, we build a simple image using [this template](https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/docker_utils.py#L123). This takes a lot of time.

When I originally wrote the ability to run conda in the docker container during the build, I was running into all sorts of permission issues, and the solution at the time was to pass the host GID and UID to the container *at build time*.

That got resolved through the build script that we're now using, which [copies to a staging area](https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/docker_utils.py#L105). However, there were cases (see https://github.com/bioconda/bioconda-recipes/issues/5027) where the build wouldn't work due to missing proxies.

At the time, I only could figure out how to use proxies by adding the `ENV` line, at build time, and so this initial most-of-the-time-it's-a-no-op build step remained.

Then a [`conda update` line](https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/docker_utils.py#L127) was added to make sure conda is the right version. It currently defaults to the [currently-installed version](https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/docker_utils.py#L382) on the host.

But the Dockerfile we're using also sets the conda version: it [copies requirements](https://github.com/bioconda/bioconda-utils/blob/master/Dockerfile#L4), which [contains the conda version](https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/bioconda_utils-requirements.txt#L4) and [installs them](https://github.com/bioconda/bioconda-utils/blob/master/Dockerfile#L10).

If we want to support proxies via docker, we can use ideas from https://elegantinfrastructure.com/docker/ultimate-guide-to-docker-http-proxy-configuration which should not require the build step.

So I'm pretty sure the step to build a container and update **can be removed.** I may have time next week to work on this and test it.

**Comment by epruesse** [comment]
Fixed in master

**Comment by epruesse** [comment]
@daler - I don't know about the proxies stuff. Please re-open if there is still need.
