### ISSUE TITLE
Bot based upload to Anaconda

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-utils#508]
@bioconda/core To save some CI time and make the upload process more reliable, I'm proposing the following updated workflow:

### Workflow:
1. The package is built on CI from the branch
2. The CI uploads artifacts to S3
3. The bot adds a comment to the PR with links to the artifacts
4. **New**: Upon `@BiocondaBot merge`, the bot uploads the packages to Anaconda, creates a merge commit with Co-Author trailer lines and pushes it to master` with `[CircleCI skip]` in the commit message.
5. If the bot is offline, a normal Github squash merge triggers CI process of building and uploading the new package.
6. If the build fails, nightly builds pick it up.

### Features:
 - CI time savings
 - minimal delay between merge and upload
 - less confusion if packages fail to build on upload jobs
 - allows enforcing 4-eyes merge policy (no self-merges)
 - old pipeline can resume if bot fails / goes offline
 - attribution of PR Co-Authors
 
### Suggested implementation of the `merge` command:
- [x] (give anaconda token to bot)
- [x] (keep copy of docker images in circleci artifacts)
- [x] check that all required status checks have succeeded
- [x] check user authorization
- [x] check that no commits were added since merge command issued
- [x] download artifacts from CircleCI 
- [x] upload packages using `anaconda upload`
- [x] upload images to quay using `skopeo`
- [x] post comment on PR indicating that packages are now uploaded
- [x] parse branch commits to determine Co-Authors
- [x] generate commit message from commits
- [x] call merge api to create squash merge commit

### Options
- [ ] delete branch?
- [x] check that merging user is not PR owner (4 eyes)
- [ ] request review from /core for new users
- [ ] make a post on gitter, indicating new package
- [ ] trigger docs rebuild
- [ ] `@biocondabot merge when ready`

**Comment by epruesse** [comment]
That should save time on the CI, avoid unnoticed errors on `master` commit builds, speed up the upload for users itching to see their packages, and be robust in case the bot is offline. The latter needed some thinking. I don't want to add another single point of failure.

**Comment by epruesse** [comment]
We could use this mechanism for more fine grained merge privileges. E.g. merging for everyone, but no self-merging unless you are in core (and a stern "grumble" from the bot if you are). Might facilitate a bit more community interaction, actually, if we and others have to ask someone to merge, rather than just clicking the button ourselves.

**Comment by epruesse** [comment]
One caveat: Biocontainers. The images are a little too big to just `docker export` as artifacts and then download and upload to quay. :-/

**Comment by epruesse** [comment]
Ok. Since part of the point is to not have secrets in the CI building, uploading the docker image from there under a temporary tag doesn't work, as nice as it sounds.

That leaves storing it as an artifact. After gzip the size seems manageable. Does anyone know a tool that can upload a docker image to a docker registry without having a docker daemon running? I would very much prefer not giving the bot access to the docker socket.

**Comment by mbargull** [comment]
> Does anyone know a tool that can upload a docker image to a docker registry without having a docker daemon running?

[`skopeo`](https://github.com/containers/skopeo) should do the job, I think.
<details><summary><code>
skopeo copy --help
</code></summary>

```
NAME:
   skopeo copy - Copy an IMAGE-NAME from one location to another

USAGE:
   skopeo copy [command options] SOURCE-IMAGE DESTINATION-IMAGE

DESCRIPTION:
   

  Container "IMAGE-NAME" uses a "transport":"details" format.

  Supported transports:
  containers-storage, dir, docker, docker-archive, docker-daemon, oci, oci-archive, ostree, tarball

  See skopeo(1) section "IMAGE NAMES" for the expected format
  

OPTIONS:
   --additional-tag value                                          additional tags (supports docker-archive)
   --quiet, -q                                                     Suppress output information when copying images
   --remove-signatures                                             Do not copy signatures from SOURCE-IMAGE
   --sign-by FINGERPRINT                                           Sign the image using a GPG key with the specified FINGERPRINT
   --format MANIFEST TYPE, -f MANIFEST TYPE                        MANIFEST TYPE (oci, v2s1, or v2s2) to use when saving image to directory using the 'dir:' transport (default is manifest type of source)
   --authfile value                                                path of the authentication file. Default is ${XDG_RUNTIME_DIR}/containers/auth.json
   --src-creds USERNAME[:PASSWORD], --screds USERNAME[:PASSWORD]   Use USERNAME[:PASSWORD] for accessing the registry
   --src-cert-dir PATH                                             use certificates at PATH (*.crt, *.cert, *.key) to connect to the registry or daemon
   --src-tls-verify value                                          require HTTPS and verify certificates when talking to the container registry or daemon (defaults to true)
   --src-shared-blob-dir DIRECTORY                                 DIRECTORY to use to share blobs across OCI repositories
   --src-daemon-host HOST                                          use docker daemon host at HOST (docker-daemon: only)
   --dest-creds USERNAME[:PASSWORD], --dcreds USERNAME[:PASSWORD]  Use USERNAME[:PASSWORD] for accessing the registry
   --dest-cert-dir PATH                                            use certificates at PATH (*.crt, *.cert, *.key) to connect to the registry or daemon
   --dest-tls-verify value                                         require HTTPS and verify certificates when talking to the container registry or daemon (defaults to true)
   --dest-shared-blob-dir DIRECTORY                                DIRECTORY to use to share blobs across OCI repositories
   --dest-daemon-host HOST                                         use docker daemon host at HOST (docker-daemon: only)
   --dest-ostree-tmp-dir DIRECTORY                                 DIRECTORY to use for OSTree temporary files
   --dest-compress                                                 Compress tarball image layers when saving to directory using the 'dir' transport. (default is same compression type as source)
```
</details>

Overall, everything around https://github.com/containers is very interesting. `podman` ("Docker without daemons") and `buildah` (`docker-build`-like but not restricted to `Dockerfile`s) -- plus the libs that back those tools -- are fast evolving and maturing projects. Esp. `buildah` is very interesting for us to use and has the potential to simplify some bits here and there.
As of now, the tools seem to do a decent job, though there can be some edges that still need ironing out. But due to their fast-moving pace (they have new minor-version releases with a good amount of additions/fixes about every month), I assume it's something we *could* use pretty soon.

**Comment by epruesse** [comment]
@mbargull That one's going to be the devil to get into the container. It's written in go and won't even build for me locally. Lots of vendor errors. :(

**Comment by bgruening** [comment]
@epruesse PPA? https://launchpad.net/~projectatomic/+archive/ubuntu/ppa
It should be also available as RPM. Creating a conda package seems to be hard.

**Comment by epruesse** [comment]
Well, the preferred method to build seems to be their docker container. That worked for me, I've got a binary that does what I need it to.

W.r.t. getting it into the bot... worst case, I add the binary to `bioconda-utils`. A little better, I upload at cargo-port and add a recipe bioconda. Haven't given up yet though.

**Comment by epruesse** [comment]
Done - https://github.com/conda-forge/staged-recipes/pull/8225 Just need someone to merge it now.

**Comment by epruesse** [comment]
Alright. https://github.com/bioconda/bioconda-recipes/pull/14958 is merged, so we should have images in the circleci artifacts soon.

**Comment by epruesse** [comment]
Once `skopeo` is in conda-forge, I'll update the bot's container and see about getting the uploads done.

Thanks @mbargull for pointing `skopeo` out! I had been googling for a while, but couldn't find anything that would do just that - copy images to docker API. And that API didn't look like I wanted to write a tool like that myself. I kind of had been hoping that the API itself would allow uploading a docker archive directly, but apparently it doesn't. Well. Got a tool do do it, that's certainly good enough.

**Comment by bgruening** [comment]
Merged! Thanks!

**Comment by epruesse** [comment]
Thanks! The bot has the binary in the new docker image. Next up is getting the merge command to also do the uploads. :)

**Comment by mbargull** [comment]
Sorry to hear the build caused you a bit of trouble. If anything else had failed, a possibility would have also been to transfer the built image's archive into another container with only `skopeo` in it and upload from there. But I'm glad to see you got it working fairly quickly so you don't have to go through those additional hoops, necessarily :).

**Comment by epruesse** [comment]
Conversing with the authors, they sounded quite happy to have their tool on conda-forge. My troubles where mostly go related. The usual first time issues.
