### ISSUE TITLE
Biocontainer Images - do we need one per Python version?

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-utils#520]
Right now, we build one Biocontainer image for each Linux variant. Unless I've missed one, the only variant pin we (actually CF) have is Python. 

Since Python is pinned as `[2.7, 3.6, 3.7]`, we get three packages and three containers for everything that needs Python and isn't noarch.

The packages are clearly required. But do we need three containers each?

**Comment by bgruening** [comment]
No, we could just pick on container. The latest one?

**Comment by epruesse** [comment]
You mean the 3.7? I think they get built in arbitrary order.

**Comment by bgruening** [comment]
Yes with the latest python version.

**Comment by dpryan79** [comment]
It was decided to keep all of the versions for the time being as any changes are liable to break nextflow.
