### ISSUE TITLE
Enforce 4-eyes principle

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-utils#521]
Self-merging has become popular and we have had merges that were sub par, broken, or not in line with out policies. IMO, not being able to self publish, or self-publishing becoming a privilege earned through hard work, is preferable to everyone over having broken packages on Bioconda

We could create a pinned issue on bioconda-recipes to poll our community for thoughts.

**Comment by kyleabeauchamp** [comment]
I am in favor of slightly increased strictness.  I think this project
should help non-experts better apply engineering best practices.

**Comment by dpryan79** [comment]
Would we want to continue allowing so many group members then? I could imagine that we either require PR reviews or instead reduce the number of members to only those with some commit threshold (this group can then merge other's PRs).

**Comment by daler** [comment]
I really like how open bioconda is, but I think we've hit thresholds in terms of package number, contributor number, and system complexity such that the openness is causing problems.

One policy could be to remove members making problematic commits. Another would be to restrict membership in the first place. Whatever we choose, it should be very clearly stated so we don't alienate anyone!

But I do think we have a large enough user base of experienced contributors to make up a trusted group so that we maintain our quick turnaround.

**Comment by bgruening** [comment]
> I really like how open bioconda is, abut I think we've hit thresholds in terms of package number, contributor number, and system complexity such that the openness is causing problems.

:+1: 

> One policy could be to remove members making problematic commits. Another would be to restrict membership in the first place. Whatever we choose, it should be very clearly stated so we don't alienate anyone!

:+1: 

My proposal would be:

+ do not add new users
+ enable "Require pull request reviews before merging"
+ allow admins to overrule this and merge PR without a review
+ if possible (not sure if this is configurable in GitHub) those admins could be a distinct group from core, a bioconda-team ... people can apply to become part of this team.
+ bulk for bioconda/core only

I do think that many people in our community do a gigantic work and keeping recipes and packages a life, even if they don't use them. We should not put extra burden on those people and simply trust them, but for new people and people not so familiar with conda and its complex build system we should require a review.

A few general things.
* I do think that a tunraround time of a few hours is still very fast.
* If it makes it easier to configure GitHub I do support of removing all users, but this should be only done if really needed and this should happen at a given data 1-2 months in the future so we can communicate this clearly.
* I do think we do a linter-hackathon (and a general one :)) and improve the linting. We can catch many errors by improving the linting.

**Comment by druvus** [comment]
I like the openness of Bioconda but I am in favor to be stricter so I support Björn's suggestion.
