### ISSUE TITLE
RTFD doesn't really work

### ISSUE THREAD

**Issue by betteridiot** [bioconda/bioconda-utils#535]
I fully acknowledge that conda-forge and bioconda are two completely different beasts. However, conda-forge seems to have some webhooks in place that autobump recipes as updates are observed on their respective package repositories (e.g. PyPI).

However, I have constantly had issues with updating my package on bioconda. This is mainly because the documentation for `bioconda-utils` seems out of sync with the current version of it. 

As it stands, there is no "easy" way for me to update my packages unless I fork the entirety of bioconda/recipes (which is a monster in-and-of-itself), create a new branch, make my sha256 and version changes to my tmeta.yml, and issue a PR. This is all because `bioconda-utils` is a little vague in what it does or how to use it. 

Can someone give me a little more guidance on this tool:
1. Since `update` is no longer an option, should I use `autobump`?
2. Does `autobump` automatically bump from PyPI?
3. Where is a template `config.yml`  that is a requirement for this call?

**Comment by epruesse** [comment]
1. Yes use autobump
2. Yes it does
3. It's in the root of bioconda-recipes.

```
bioconda-utils autobump recipes/ config.yml --packages <name-of-my-package> --create-pr --dry-run
```

**Comment by betteridiot** [comment]
Thank you fr the prompt reply

**Comment by epruesse** [comment]
If you want to update docs - please do. Perhaps there will be a cloud version at some point that runs automatically. For now, certain problems in conda-forge itself make that impossible - it just takes too long to render recipes. Also `autobump` looks for dependency changes. For PyPI that means running unknown code, because the `setup.py` has to be executed. That needs a lot of sandboxing...

**Comment by epruesse** [comment]
Err, conda-build, not conda-forge.

**Comment by betteridiot** [comment]
The biggest issue is that I am unfamiliar with the differences in implementation between conda-forge and bioconda

**Comment by epruesse** [comment]
Completely separate. All of our tooling is in bioconda-utils. CF tooling is split among many places. We have one big repo, they have many thousands of small repos. Both approaches have pros and cons.
