### ISSUE TITLE
Lint: handle cython

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-utils#549]
Not sure where cython needs to go, but if it's there, it probably needs the C compiler...

E.g. https://github.com/bioconda/bioconda-recipes/pull/15497

**Comment by dpryan79** [comment]
:+1: We should probably keep it under `host:`, since it's accompanying `python` from there.

**Comment by epruesse** [comment]
Technically, `cython` converts `pyx/pvd` to `c/h`, which is platform unspecific. But yes, it might to so differently between py2/py3. Not sure. For pip, it's common to distribute the cythonized code, so with c files already generated, so that cython isn't needed on the install side.

**Comment by epruesse** [comment]
Fixed in 278557b5344413d096d1e6bad4e1fc3f6a794fe8
