### ISSUE TITLE
noarch python LINT check triggered for non-Python noarch recipes

### ISSUE THREAD

**Issue by cbrueffer** [bioconda/bioconda-utils#559]
Non-Python noarch recipes containing Python wrapper scripts can trigger the `noarch: python` LINT check; see https://github.com/bioconda/bioconda-recipes/pull/15646 and https://github.com/bioconda/bioconda-recipes/pull/15625

**Comment by epruesse** [comment]
@mbargull What does the `noarch: python` do exactly? Should a package that just contains a python wrapper script be `noarch: generic` or `noarch: python`?

**Comment by epruesse** [comment]
Hmm. It looks like the base structure is different, with `site-libraries` at top level, to avoid `pythonX.Y/site-libraries` I assume.

**Comment by epruesse** [comment]
Fixed in 5fcfe0338d53e3d1e1fc54521273100a016ed33f
