### ISSUE TITLE
PackagesNotFoundError, following setup docs

### ISSUE THREAD

**Issue by tmatthew** [bioconda/bioconda-utils#584]
After a fresh install of Anaconda, I ran into trouble at step 3 of [Getting Started](https://bioconda.github.io/user/install.html#install-conda).  Installing bwa a directed gave me some trouble:
```
C:\Users\test>conda install bwa
WARNING conda.base.context:use_only_tar_bz2(632): Conda is constrained to only using the old .tar.bz2 file format because you have conda-build installed, and it is <3.18.3.  Update or remove conda-build to get smaller downloads and faster extractions.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - bwa

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/win-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
  - https://conda.anaconda.org/r/win-64
  - https://conda.anaconda.org/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by npavlovikj** [comment]
@tmatthew , are you trying to install `bwa` on a Windows machine? Bioconda builds packages only for Linux and OSX, and not Windows.

**Comment by tmatthew** [comment]
Yes, that is the case.  What are the recommendations for windows users?

**Comment by npavlovikj** [comment]
@tmatthew , I think most of the bioinformatics tools were built with Linux in mind, so you will hardly find Windows support. It might be easier if you start Linux VM on your Windows machine. If you still want to use Windows, you can not use `bioconda`, but you will need to compile `bwa` yourself. Looks like there is some thread about `bwa` on Windows, http://seqanswers.com/forums/showthread.php?t=20025, but I don't know how recently updated this documentation is.
