### ISSUE TITLE
a contribute link is broken in the  README

### ISSUE THREAD

**Issue by jarnolaitinen** [bioconda/bioconda-utils#595]
This is 404: https://bioconda.github.io/contribute-a-recipe.html
Perhaps to here? https://bioconda.github.io/contributor/index.html

**Comment by dpryan79** [comment]
Is this in the documentation or the template for pull requests? Either way, just give me a link and I can get this fixed (we've found a few of these recently :( ).

**Comment by jarnolaitinen** [comment]
Hello, 

The broken link is in 
https://github.com/bioconda/bioconda-recipes/blob/master/README.md

Also in  
https://bioconda.github.io/user/install.html
there is a broken link to
 https://conda.io/en/latest/building/recipe.html#conda-recipe-files-overview 
and in Section 1 
https://conda.io/en/latest/faq.html
and  Section 5 
https://bioconda.github.io/user/_static/badge-generator/

Thanks!
