### ISSUE TITLE
Conda environment variables not exported to container

### ISSUE THREAD

**Issue by sebastian-luna-valero** [bioconda/bioconda-utils#63]
Hello,

I have initially reported the issue at `bioconda-recipes`:
https://github.com/bioconda/bioconda-recipes/issues/3780

but I think this is the correct forum.

I have a new recipe which uses `SRC_DIR` to run tests. `SRC_DIR` is a `conda` environment variable:
https://conda.io/docs/building/environment-vars.html

but it is not available when running `simulate-travis.py`.

Is this the intented behaviour?

Many thanks,
Sebastian

**Comment by daler** [comment]
Answered over in bioconda/bioconda-recipes#3780
