### ISSUE TITLE
contributing GitHub / Bioconductor package

### ISSUE THREAD

**Issue by LiNk-NY** [bioconda/bioconda-utils#633]
Hi Bioconda team,
I'd like to contribute a Bioconductor deps / GitHub package to bioconda (see here: 
https://github.com/waldronlab/cBioPortalData).

I am a Bioconductor developer and I am not familiar with the bioconda _MO_. 
I have already created a GitHub release for the package. My initial thinking was that
it shouldn't be hard to link the binary in the generated skeleton but my initial thinking
is usually wrong :grin: 

The instructions here https://bioconda.github.io/contributor/guidelines.html#r-other-sources
are not clear enough for me to obtain / run the `bioconductor-skeleton` on a
GitHub package. I am also getting conflict issues with the installation of `bioconda-utils`. 

Your help is appreciated. 
Best,
Marcel

**Comment by dpryan79** [comment]
The bioconductor skeleton only works with bioconductor packages, not those in github. In this case you would need to manually write the recipe, which is a bit annoying but not the end of the world. If you'll be submitting this to CRAN or Bioconductor anyway though, I strongly encourage you to simply wait until the package is there, as the skeletons will then work appropriately.

**Comment by LiNk-NY** [comment]
Hi Devon, @dpryan79 
Thanks for your help!

Is there a way to include GitHub dependencies that are not already in bioconda? 

I imagine they would go under `requirements`:
```
requirements:
  host:
    - r-base
  run:
    - r-base
```

**Comment by LiNk-NY** [comment]
This is what I have so far: 
https://github.com/LiNk-NY/bioconda-recipes/tree/master/recipes/r-cbioportaldata

**Comment by npavlovikj** [comment]
"bioconda" recognizes packages/dependencies that are in the "bioconda", "conda-forge" and "defaults" channels, https://bioconda.github.io/user/install.html#set-up-channels, so as long as your dependencies are in one of those 3 channels, you are ok. If they are not, we just need to add them to "conda-forge" or "bioconda" :)
"r-base" is already in "conda-forge", so you are good - and adding it in both `host` and `run` sections is the right way.
There are lots of R/bioconductor examples in https://github.com/bioconda/bioconda-recipes/tree/master/recipes, so you can take a look at some for reference.

**Comment by npavlovikj** [comment]
Looks like you are missing `sha256` in the `source` section of your current recipe, https://bioconda.github.io/contributor/guidelines.html#hashes, but once you add that, please feel free to submit PR to bioconda - the recipe looks ok.

**Comment by LiNk-NY** [comment]
I suppose there is no easy way to include GitHub dependencies since `bioconda` requires built binaries. 
It looks like I'd have to add these "GitHub" R packages the same way I am including `r-cbioportaldata` **before** I actually include my target package.
Thanks for your help Natasha @npavlovikj

**Comment by npavlovikj** [comment]
Yes, both "AnVIL" and "AnVIL_rapiclient" can be added the same way.

**Comment by LiNk-NY** [comment]
*update*: We will hold of until these packages are released in Bioconductor and then port them over to bioconda. Thanks!
