### ISSUE TITLE
Handle blas/lapack in bioconductor skeleton

### ISSUE THREAD

**Issue by dpryan79** [bioconda/bioconda-utils#647]
At some point in time, r-base on OSX changed the blas implementation or version that it links against. That wasn't an issue for most packages, but a fair number of CRAN (and apparently also Bioconductor) packages seem to require one or both of these without listing that dependency. This has caused a number of random failures related to missing libopenblasp both here and (more frequently) on conda-forge. Given that, I propose adding `{{ blas }}` and `{{ lapack }}` to the host section of all compiled Bioconductor packages in the May roll-out. That will hopefully prevent this sort of thing from happening in the future.

**Comment by mbargull** [comment]
SGTM.
We would want to use
```yaml
requirements:
  host:
    - blas
    - lapack
```
then (https://conda-forge.org/docs/maintainer/knowledge_base.html#blas).

https://conda-forge.org/docs/user/announcements.html?highlight=blas
> 2019-03-28: We overhauled the blas support in conda-forge.
> - Our packages now build against NETLIB’s reference implementation.
> - You as a user can now choose the implementation available at runtime.
> 
> For more information please refer to the [documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html#knowledge-blas).
