### ISSUE TITLE
Autobump incorrectly parses some URLs

### ISSUE THREAD

**Issue by dpryan79** [bioconda/bioconda-utils#701]
The reason a number of recipes are skipped during autobump is that it doesn't parse their prefixes correctly. This just happened with bioconda-utils, where it parsed the URL as follows:

    GithubTag matched https://github.com/bioconda/bioconda-utils/archive/v0.16.22.tar.gz with {'account': 'bioconda', 'project': 'bioconda-utils', 'prefix': '', 'version': '0.16.22', 'ext': '.tar.gz'}

For some reason `prefix` isn't getting set to `v`, so when it's parsing `https://github.com/bioconda/bioconda-utils/tags` it reports `bioconda-utils has no URL in source 1 recognized by any Hoster class`.

**Comment by dpryan79** [comment]
The cause is partially due to a non-capture group (`(?:(?<=[/._-])[rv])?`) added between the prefix and the version via the inherited version_pattern. Removing that fills in the appropriate prefix, though it's still not used.

**Comment by mbargull** [comment]
Oh, hovering over the archive links at https://github.com/bioconda/bioconda-utils/releases it looks like GitHub may have changed the default links to `../archive/refs/tags/<tag>.tar.gz` from `.../archive/<tag>.tag.gz`, e.g., https://github.com/bioconda/bioconda-utils/archive/refs/tags/v0.16.23.tar.gz

**Comment by mbargull** [comment]
I'm not really familiar with the autobump/`hosters.py` code.
Would a
```diff
-    link_pattern = r"/{account}/{project}/archive/{tag}{ext}"
+    link_pattern = r"/{account}/{project}/archive(/refs/tags)?/{tag}{ext}"
```
suffice or do we need to do anything more with that `prefix_pattern` stuff?

**Comment by dpryan79** [comment]
Maybe? I'm also not familiar with that code, I looked at it for the first time today when trying to track this down.

**Comment by mbargull** [comment]
> I looked at it for the first time today when trying to track this down.

Same :).
But yep, I tried it out and gh-703. Fixes that.

**Comment by epruesse** [comment]
Sorry - saw this too late

**Comment by mbargull** [comment]
Hey Elmar! No worries, all good ;).

**Comment by epruesse** [comment]
Yes - I'm alive... ;-)
