### ISSUE TITLE
LOCKERROR: It looks like conda is already doing something.

### ISSUE THREAD

**Issue by sebastian-luna-valero** [bioconda/bioconda-utils#72]
Having this problem here:
https://travis-ci.org/bioconda/bioconda-recipes/jobs/206522192#L576
https://travis-ci.org/bioconda/bioconda-recipes/jobs/206536065#L480

I have reported to conda:
https://github.com/conda/conda/issues/3981

**Comment by glormph** [comment]
I got this as well today, and was suspecting it had something to do with the S3 outage earlier.

**Comment by glormph** [comment]
Error seems to have disappeared now, at least when restarting a build in my own repo.

**Comment by sebastian-luna-valero** [comment]
Here is the feedback from the conda team:

> These specific locks have all been removed in conda 4.3. I think upgrading to 4.3 is the best solution at this point. Latest version is 4.3.13.

I am sure we must be using conda 4.2 for a reason in bioconda, is that right?

**Comment by daler** [comment]
Automatically using the latest version has caused problems in the past, so we keep it pinned to avoid surprises. I'm not sure we've tested 4.3 yet.

If you'd like to help with testing, create a new bioconda-utils branch that updates the version here: 
https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/bioconda_utils-requirements.txt

and then in a new bioconda-recipes branch, point to your new bioconda-utils branch here:

https://github.com/bioconda/bioconda-recipes/blob/master/.travis.yml#L20

**Comment by sebastian-luna-valero** [comment]
Sure, thanks @daler 

Testing here https://github.com/bioconda/bioconda-utils/pull/73

**Comment by sebastian-luna-valero** [comment]
This issue can now be closed.
