### ISSUE TITLE
Bioconda pins an outdated version of libdeflate from conda-forge

### ISSUE THREAD

**Issue by jmarshall** [bioconda/bioconda-utils#720]
Conda-forge recently bumped their libdeflate package to 1.8, in conda-forge/libdeflate-feedstock#14 in mid-July.

_bioconda_utils/bioconda_utils-conda_build_config.yaml_ pins libdeflate 1.7. This means that as other conda-forge packages are rebuilt to use libdeflate-1.8, in time libdeflate-1.7 will fall out of conda-forge's _current_repodata.json_ and bioconda packages that depend on libdeflate will become susceptible to conda/conda#9905 / bioconda/bioconda-recipes#24199 once again.

Bioconda packages that directly depend on libdeflate (notably htslib and staden_io_lib) will need to be rebuilt against 1.8 before this happens. However first either the pinning in _bioconda_utils-conda_build_config.yaml_ needs to be updated to 1.8 or the libdeflate pinning needs to be removed. (In my non-expert opinion, pinning a package from outwith bioconda seems unwise. So I would be interested in the reason for pinning libdeflate.)

**Comment by dpryan79** [comment]
Thanks for the heads up, we'll probably be updating the pinnings later in the year anyway, so this can wait for that.

**Comment by jmarshall** [comment]
The situation is already worse than I expected. There is one (1) remaining conda-forge package in their _current_repodata.json_ that requires libdeflate-1.7.

When libtiff is updated (on their [current schedule](https://gitlab.com/libtiff/libtiff/-/tags) that could be next month), libdeflate-1.7 will drop out of conda-forge's _current_repodata.json_. When that happens, bioconda users using `conda create -ntmp samtools` will be given old versions of samtools that don't work due to the _libcrypto_ / bad old _openssl_ version issue.

I'm not sure that “probably later in the year” is going to be soon enough for libdeflate.

**Comment by jmarshall** [comment]
Since #734, _bioconda_utils/bioconda_utils-conda_build_config.yaml_ pins libdeflate 1.9.

As of conda-forge/libdeflate-feedstock#16 on Feb 7th, conda-forge supplies libdeflate 1.10. Sometime between then and now, libdeflate-1.9 has fallen out of conda-forge's _current_repodata.json_ (this currently contains 1.7, 1.8, and 1.10).

Bioconda's current version of pysam is built against our currently pinned 1.9, which means that due to bioconda/bioconda-recipes#24199, running `conda create -n tmp pysam` chooses an outdated version of pysam — the known-buggy 0.16.0.1, which was built against libdeflate 1.7. This is the cause of https://github.com/pysam-developers/pysam/issues/1081#issuecomment-1038836161.

Luckily bioconda has htslib 1.14 builds using both libdeflate 1.7 and 1.9, so currently `conda create -n tmp htslib` does choose the current 1.14 version (but the `_0` 1.7 build rather than the latest `_1` 1.9 build). However htslib 1.15 is now fairly imminent and if it is built against libdeflate 1.9 only it will never be chosen without explicitly specifying the version.

@dpryan79: I believe the best fix for this is to bump bioconda's libdeflate pinning to 1.10 as a matter of urgency. (Though one does wonder if there may be an imminent 1.10.1 due to ebiggers/libdeflate#165.)

**Comment by dpryan79** [comment]
@jmarshall Ugh, I hate this "feature" of the conda solver. Thanks for the heads up, yeah, we need to update the pinnings...yet again...to avoid this annoyance. At least that will be a quick migration. I'll try to start that this weekend.

**Comment by dpryan79** [comment]
BTW, this should hopefully get rid of this whole issue: https://github.com/conda/conda/pull/11193

**Comment by jmarshall** [comment]
Note that as of conda-forge/conda-forge-pinning-feedstock#2528 a couple of days ago, libdeflate is pinned in conda-forge-pinning-feedstock (currently at 1.10).

**Comment by jmarshall** [comment]
Now very well fixed. Huzzah! 🎉
