### ISSUE TITLE
Thoughts on tool description in Bot's auto bump PR?

### ISSUE THREAD

**Issue by rpetit3** [bioconda/bioconda-utils#730]
Purely a _want_ and not a _need_, but I think it would be incredibly useful to add the tool description to the auto bump PR. I realize I can just look at the YAML or click the link, but this would allow PR reviewers to quickly learn about the tools.

Current Format
---

Update [`immuneml`](https://bioconda.github.io/recipes/immuneml/README.html): **2.0.5** &rarr; **2.0.6**

[![install with bioconda](https://img.shields.io/badge/install%20with-bioconda-brightgreen.svg?style=flat)](http://bioconda.github.io/recipes/immuneml/README.html) [![Conda](https://img.shields.io/conda/dn/bioconda/immuneml.svg)](https://anaconda.org/bioconda/immuneml/files)

Info | Link
-----|-----
Recipe | [`recipes/immuneml`](https://github.com//bioconda/bioconda-recipes/tree/bump/immuneml/recipes/immuneml) (click to view/edit other files)
Releases |[https://pypi.org/pypi/immuneML/json](https://pypi.org/pypi/immuneML/json)
Recipe Maintainer(s) | xyz
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

---

Proposed Format
---

Update [`immuneml`](https://bioconda.github.io/recipes/immuneml/README.html): **2.0.5** &rarr; **2.0.6**

[![install with bioconda](https://img.shields.io/badge/install%20with-bioconda-brightgreen.svg?style=flat)](http://bioconda.github.io/recipes/immuneml/README.html) [![Conda](https://img.shields.io/conda/dn/bioconda/immuneml.svg)](https://anaconda.org/bioconda/immuneml/files)

Info | Link
-----|-----
Recipe | [`recipes/immuneml`](https://github.com//bioconda/bioconda-recipes/tree/bump/immuneml/recipes/immuneml) (click to view/edit other files)
Description | immuneML is a software platform for machine learning analysis of immune receptor repertoires.
Releases |[https://pypi.org/pypi/immuneML/json](https://pypi.org/pypi/immuneML/json)
Recipe Maintainer(s) | xyz

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

---

**Comment by dpryan79** [comment]
Migrated to bioconda-utils since this is the source of the auto-generated PRs.

@mbargull @epruesse Any guesses how difficult this would be to implement? I assume this would mostly be changes in `templates/autobump_pr.md`

**Comment by marcelm** [comment]
I hope it’s appropriate to add another suggestion here: It would be really useful to also have a direct link to the home page (the `about: home:` URL). When reviewing bot-generated PRs, the first thing I do is to check whether the dependencies have changed, and that usually means going to the homepage (typically a GitHub repository).

**Comment by rpetit3** [comment]
This is amazing! Thank you very much!
