### ISSUE TITLE
linting issues

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-utils#76]
Tracking some TODOs as problems arise:

OS-specific version detection: If linux finishes and upload before OSX (which happens frequently), the OSX run complains that it already exists (like [here](https://travis-ci.org/bioconda/bioconda-recipes/jobs/208565093)). Solution is to temporarily disable the "already_in_bioconda" lint, which is done [here](https://github.com/bioconda/bioconda-utils/pull/75/commits/b3ee6dea16ae9940bc19c459a0f3c4463439b01e)

We need to simulate git commit history in the tests to better test `utils.modified_recipes`.

**Comment by epruesse** [comment]
I assume this has been fixed.
