### ISSUE TITLE
Docker Containers for Reproducible Research Workshop (C4RR)

### ISSUE THREAD

**Issue by sebastian-luna-valero** [bioconda/bioconda-utils#81]
Hi @bioconda/core 

There is this workshop coming:
https://www.software.ac.uk/c4rr

and I thought it could be interesting to present the bioconda project. What do you think?

Best regards,
Sebastian

**Comment by johanneskoester** [comment]
Definitely. Unfortunately, I won't be available at that time. If I am not mistaken, we have several people from Wellcome Trust Centre (Hinxton) and Oxford University. They could go there easily. Or does anybody from @bioconda/core want?

**Comment by sebastian-luna-valero** [comment]
Thanks @johanneskoester 

I am planning to go anyway but I have not been that much involved in the core of the project. If it is not possible for any core member to attend, I might volunteer to present this project (as a lightning talk), but would appreciate guidance to do it properly. The deadline is 31st March 2017 at midnight.

Please let me know your thoughts.

**Comment by johanneskoester** [comment]
Sounds good to me.
I always have 6 slides about Bioconda in my Snakemake presentations. They should be suitable for a quick summary of the project:
https://slides.com/johanneskoester/snakemake-juelich/live#/26

Does that help?

**Comment by sebastian-luna-valero** [comment]
Great! 

Instead of the slides above, I think the following presentation is more comprehensive:
http://slides.com/johanneskoester/bioconda

On the other hand, as [C4RR](https://www.software.ac.uk/c4rr) is about containers, I thought we should mention:
* bioconda uses container to build and test software packages in a clean, predictable environment (via `bioconda-utils`). 
* bioconda packages are provided as tarballs and containers (https://github.com/bioconda/bioconda-recipes/issues/2297)

Will I be lucky enough to get some slides about how this is done? The `bioconda-utils` part is the one that I do not control and I think is equally relevant to the workshop.

Does anyone know whether the `conda-forge` people are going to attend/present as well? There might be overlap between `conda-forge` and `bioconda` if that's the case.

**Comment by bgruening** [comment]
@sebastian-luna-valero I can provide some slides about the BioContainers part and how we create containers for every single Conda package. @ypriverol will most likely also be there and help you. He is from the BioContainers community.

**Comment by sebastian-luna-valero** [comment]
Brilliant, many thanks @bgruening @ypriverol

**Comment by ypriverol** [comment]
I already submit the BioConda+BioCotnainers abstract . Hope will be accepted ;) . If is accepted I will circulate my slides before my talk.

**Comment by sebastian-luna-valero** [comment]
Thanks @ypriverol 

If @bioconda/core is happy with that, please feel free to close this issue.

**Comment by sebastian-luna-valero** [comment]
@ypriverol I would be grateful if you could share your slides at some point!

**Comment by bgruening** [comment]
@sebastian-luna-valero our slides from last week are here: https://f1000research.com/slides/6-1203

**Comment by sebastian-luna-valero** [comment]
Many thanks @bgruening

I attended the C4RR workshop in Cambridge a month ago and I was surprised that bioconda was not mentioned at all. I discussed it with some people at the conference, explaining the advantages of (bio)conda for CLI tools, but most were interested in learning about containers only and did not show huge interest. 

Fair enough. Although I agree that containers have an important role to play in application deployment in general, I still believe that (bio)conda is a much better approach when all you need is a reproducible environment via CLI.

I ended up writing a [blog post](https://cgatoxford.wordpress.com/2017/05/12/the-dependency-hell-in-software-development/) just to express my opinions, help a bit spreading the word about (bio)conda and acknowledge the great work that you guys are doing.

**Comment by ypriverol** [comment]
Hi Sebastian:
 The Idea of Singularity (which probably was the main attention of the Conference in Cambridge) is that they want to be a focus on Science not only BioMedical Science. This is probably the main reason why 
 they are not talking about any specific field. 

Regards
Yasset

**Comment by bgruening** [comment]
@sebastian-luna-valero the nice thing is and I hope our slides delivered this message, that BioConda is ideal to create containers.
