### ISSUE TITLE
BiocondaBot merge seems broken

### ISSUE THREAD

**Issue by acaprez** [bioconda/bioconda-utils#905]
Hi,

It appears the `BiocondaBot please merge` functionality is broken - for example [here](https://github.com/bioconda/bioconda-recipes/actions/runs/5609369281/job/15196828215) and [here](https://github.com/bioconda/bioconda-recipes/actions/runs/5616618966/job/15219280141).  

It looks to be a missing library issue with the `node` binary:
```
/usr/bin/docker exec  7f3221262fcb1a81a69213af17a8f1c7e82ada35b6294956e5833f111c5ee9ff sh -c "cat /etc/*release | grep ^ID"
/__e/node16/bin/node: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

**Comment by dpryan79** [comment]
Interesting, it's trying to post a comment saying it's deprecated but apparently the github action we use to do that has a bug in the corresponding container.
